#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Convert 'samenvatting.docx' to a self-contained sibling HTML page.

Usage: python convert_samenvatting.py [paragraph_folder_path]
       python convert_samenvatting.py --all   (processes all paragraphs)

HOW IT WORKS
============
The samenvatting docx is generated by build-scripts/content/book-1/b1-<para>-samenvatting.js
as a 3-row x 2-col infographic-table layout. This converter walks the docx's
top-level tables (1 banner table + 3 row-tables, each row table is 1x3 with
[left, spacer, right]), extracts 6 cell records, and emits a sibling .html
with the same six logical sections.

CELL DOMAIN MAPPING is hard-wired per the b1-111-samenvatting.js contract.
For paragraphs whose samenvatting builder uses a different cell-domain layout,
extend SAMENVATTING_CELL_DOMAINS or pass it via a per-paragraph override map.

Note: this converter emits .samenvatting-cell / .samenvatting-grid / .cell-*
hooks that are not yet styled in engines/voorkennis.css. Without a follow-up
CSS commit the page renders as a vertical stack of unboxed sections - content
is correct, layout is degraded. See L1.5D plan SS D1-2 for the CSS commit.
"""
import sys, io, os, glob, html as html_mod, re
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
from docx import Document
from docx.oxml.ns import qn

# Domain -> color mapping (copied from convert_voorkennis.py).
DOMAIN_MAP = {
    'Wiskundig':        ('wiskunde',   '#1A5276', '#EBF5FB', '#154360'),
    'Economisch':       ('economisch', '#E67E22', '#FEF5E7', '#BA6A1C'),
    'Grafisch':         ('grafisch',   '#1E8449', '#E8F8F0', '#186A3B'),
    'Bedrijfseconomie': ('bedrijf',    '#E67E22', '#FEF5E7', '#BA6A1C'),
    'Marktanalyse':     ('markt',      '#1A5276', '#EBF5FB', '#154360'),
    'Marktwerking':     ('marktwerk',  '#1A5276', '#EBF5FB', '#154360'),
    'Overheidsbeleid':  ('overheid',   '#1E8449', '#E8F8F0', '#186A3B'),
    'Arbeidsmarkt':     ('arbeids',    '#E67E22', '#FEF5E7', '#BA6A1C'),
    'Externe effecten': ('extern',     '#1E8449', '#E8F8F0', '#186A3B'),
    'Pitfall':          ('pitfall',    '#D9534F', '#FDE8E8', '#A33D3A'),
}

# Editorial 9-domain -> 3-shared collapse (copied from convert_vaardigheden.py
# and extended with 'pitfall' which collapses to economisch since pitfalls are
# colored via .callout-letop, not via a domain class).
SHARED_DOMAIN_TOKENS = {
    'wiskunde':   'wiskunde',
    'economisch': 'economisch',
    'grafisch':   'grafisch',
    'bedrijf':    'economisch',
    'markt':      'wiskunde',
    'marktwerk':  'wiskunde',
    'overheid':   'grafisch',
    'arbeids':    'economisch',
    'extern':     'grafisch',
    'pitfall':    'economisch',
}

# Per b1-111-samenvatting.js (lines 11-15) the 6 cells map to these author
# domains. cells 0,1 economisch (teal); cell 2 wiskundig (blue alt-kosten);
# cell 3 pitfall (amber warning); cells 4,5 grafisch (green procedure +
# worked example). For future paragraphs whose samenvatting builder differs,
# extend this with a per-paragraph override.
SAMENVATTING_CELL_DOMAINS = ['Economisch', 'Economisch', 'Wiskundig', 'Pitfall', 'Grafisch', 'Grafisch']


def get_domain_info(domain_name):
    """Return (css_class, primary, light, dark) for a domain name."""
    if domain_name in DOMAIN_MAP:
        return DOMAIN_MAP[domain_name]
    slug = domain_name.lower().replace(' ', '')[:8]
    return (slug, '#1A5276', '#EBF5FB', '#154360')


def shared_domain_class(domain_name):
    """Return one of {wiskunde, economisch, grafisch} for any domain name."""
    slug = get_domain_info(domain_name)[0]
    return SHARED_DOMAIN_TOKENS.get(slug, 'economisch')


def esc(text):
    return html_mod.escape(text)


def find_web_variant_bases(assets_dir):
    """Return asset bases that have both web light and dark SVG variants."""
    bases = set()
    if os.path.isdir(assets_dir):
        for svg in glob.glob(os.path.join(assets_dir, '*_web_light.svg')):
            base = os.path.basename(svg).replace('_web_light.svg', '')
            if os.path.exists(os.path.join(assets_dir, base + '_web_dark.svg')):
                bases.add(base)
    return bases


def render_asset_image(asset_prefix, payload, web_variant_bases):
    """Render an asset image, using themed web variants when available.

    L1.5V Bucket A4: payload is now {'base': str, 'alt': str}.
    """
    if isinstance(payload, dict):
        base = payload['base']
        alt = payload['alt']
    else:
        base = payload
        alt = payload
    if base in web_variant_bases:
        light_src = f'{asset_prefix}/{esc(base)}_web_light.svg'
        dark_src = f'{asset_prefix}/{esc(base)}_web_dark.svg'
        fallback_src = f'{asset_prefix}/{esc(base)}.svg'
        return (
            '        <figure class="asset-figure">\n'
            f'          <img src="{light_src}" data-light-src="{light_src}" '
            f'data-dark-src="{dark_src}" data-fallback-src="{fallback_src}" '
            f'alt="{esc(alt)}" class="asset-svg">\n'
            '        </figure>\n'
        )
    return (
        '        <figure class="asset-figure">\n'
        f'          <img src="{asset_prefix}/{esc(base)}.svg" '
        f'alt="{esc(alt)}" class="asset-svg">\n'
        '        </figure>\n'
    )


def extract_assets_from_paragraph(p):
    """Walk a paragraph for inline images carrying alt-text.

    L1.5V Bucket A4: builders emit `descr="asset-alt:<text>"`. Returns a list
    of {'base': str, 'alt': str} dicts; legacy `asset:<id>` returns
    {'base': id, 'alt': id} with a stderr warning.
    """
    out = []
    for run in p.runs:
        blips = run._element.findall('.//' + qn('a:blip'))
        if blips:
            drawing = run._element.find('.//' + qn('wp:inline'))
            if drawing is not None:
                docPr = drawing.find(qn('wp:docPr'))
                if docPr is not None:
                    descr = docPr.get('descr', '') or ''
                    title = docPr.get('title', '') or ''
                    if descr.startswith('asset-alt:'):
                        alt = descr[len('asset-alt:'):]
                        base = title or alt[:30]
                        out.append({'base': base, 'alt': alt})
                    elif descr.startswith('asset:'):
                        base = descr[len('asset:'):]
                        sys.stderr.write(
                            f"WARNING: legacy 'asset:' prefix for {base!r} in samenvatting "
                            f"(migrate builder to pass altText).\n"
                        )
                        out.append({'base': base, 'alt': base})
    return out


def extract_cell_content(cell):
    """Extract a generic content stream from a docx cell.
    Returns a dict with 'heading', 'paragraphs' (list of plain text), 'assets'
    (list of asset_name strings encountered in cell paragraphs), and
    'inner_tables' (list of list-of-lists for any nested tables).
    """
    paragraphs = []
    assets = []
    heading = ''
    for i, p in enumerate(cell.paragraphs):
        text = p.text.strip()
        # Asset images: pull alt-text 'asset:NAME'
        for asset_name in extract_assets_from_paragraph(p):
            if asset_name not in assets:
                assets.append(asset_name)
        if not text:
            continue
        if not heading:
            heading = text
        else:
            paragraphs.append(text)

    inner_tables = []
    for t in cell.tables:
        rows = []
        for row in t.rows:
            row_cells = [c.text.strip() for c in row.cells]
            rows.append(row_cells)
        inner_tables.append(rows)

    return {
        'heading': heading,
        'paragraphs': paragraphs,
        'assets': assets,
        'inner_tables': inner_tables,
    }


def parse_document(docx_path):
    """Return a dict with banner data and a list of 6 raw cell records."""
    doc = Document(docx_path)
    tables = doc.tables

    # Banner: 1x1, two text lines separated by a soft line break.
    banner = {'title_line': '', 'subtitle_line': ''}
    if len(tables) >= 1 and len(tables[0].rows) >= 1 and len(tables[0].rows[0].cells) >= 1:
        banner_text = tables[0].rows[0].cells[0].text
        lines = [l.strip() for l in banner_text.split('\n') if l.strip()]
        if lines:
            banner['title_line'] = lines[0]
            if len(lines) > 1:
                banner['subtitle_line'] = lines[1]

    # 3 row tables, each 1x3 with [left, spacer, right]; spacer (cell index 1)
    # is empty by builder contract and we skip it.
    cells = []
    for ti in range(1, 4):
        if ti >= len(tables):
            break
        t = tables[ti]
        if len(t.rows) < 1:
            continue
        row = t.rows[0]
        if len(row.cells) >= 1:
            cells.append(extract_cell_content(row.cells[0]))
        if len(row.cells) >= 3:
            cells.append(extract_cell_content(row.cells[2]))

    return {'banner': banner, 'cells': cells}


def build_data_from_doc(docx_path, para_number, para_name):
    """Convert parsed cells into the 6-section logical structure used by
    generate_html. Hard-wires cell domains via SAMENVATTING_CELL_DOMAINS."""
    parsed = parse_document(docx_path)
    title = para_name
    subtitle = parsed['banner']['subtitle_line'] or 'Samenvatting'

    sections = []
    for i, raw in enumerate(parsed['cells']):
        domain = SAMENVATTING_CELL_DOMAINS[i] if i < len(SAMENVATTING_CELL_DOMAINS) else 'Economisch'
        sections.append({
            'index': i + 1,
            'domain': domain,
            'shared_domain': shared_domain_class(domain),
            'heading': raw['heading'],
            'paragraphs': raw['paragraphs'],
            'assets': raw['assets'],
            'inner_tables': raw['inner_tables'],
        })

    return {
        'number': para_number,
        'title': title,
        'subtitle': subtitle,
        'sections': sections,
    }


def render_inner_table_html(rows):
    """Render a docx-cell inner table as a basic HTML table."""
    if not rows:
        return ''
    out = ['        <table class="cell-table">']
    # Treat first row as header.
    out.append('          <thead><tr>')
    for h in rows[0]:
        out.append(f'            <th>{esc(h)}</th>')
    out.append('          </tr></thead>')
    out.append('          <tbody>')
    for r in rows[1:]:
        out.append('            <tr>')
        for c in r:
            out.append(f'              <td>{esc(c)}</td>')
        out.append('            </tr>')
    out.append('          </tbody>')
    out.append('        </table>')
    return '\n'.join(out) + '\n'


def render_pitfall_callout(line):
    """Render a single ✘-prefixed pitfall paragraph as a callout-letop block.
    Body is split on the first '.  ' or '. ' into <strong>title</strong> + rest;
    if no clean split is found the whole text becomes the body."""
    text = line.lstrip('✘').strip()
    # Split on first sentence boundary (period followed by 1+ spaces).
    m = re.match(r'^(.+?\.)\s+(.*)$', text)
    if m:
        title_html = f'<strong>{esc(m.group(1))}</strong> '
        body_html = esc(m.group(2))
    else:
        title_html = ''
        body_html = esc(text)
    return (
        '        <div class="callout callout-letop">\n'
        '          <span class="callout-icon">&#9888;&#65039;</span>\n'
        f'          <div class="callout-body">{title_html}{body_html}</div>\n'
        '        </div>'
    )


def render_section_body(section, asset_prefix, web_variant_bases):
    """Render the inner HTML of one .samenvatting-cell."""
    parts = []
    is_pitfalls_cell = section.get('domain') == 'Pitfall'
    for para in section['paragraphs']:
        if is_pitfalls_cell and para.lstrip().startswith('✘'):
            parts.append(render_pitfall_callout(para))
        else:
            parts.append(f'        <p class="cell-para">{esc(para)}</p>')
    for itable in section['inner_tables']:
        parts.append(render_inner_table_html(itable))
    for asset_name in section['assets']:
        parts.append(render_asset_image(asset_prefix, asset_name, web_variant_bases))
    return '\n'.join(parts) + '\n' if parts else ''


def generate_html(data, para_number, para_name, asset_prefix='_assets',
                  shared_prefix=None, web_variant_bases=None):
    """Generate the standalone web HTML for the samenvatting page."""
    if web_variant_bases is None:
        web_variant_bases = set()
    if not shared_prefix:
        shared_prefix = '../../shared'

    # Hero
    docx_filename = f'{para_number} {para_name} – samenvatting.docx'
    hero = (
        '  <header class="hero">\n'
        '    <div class="hero-inner">\n'
        '      <a class="back-link" href="../index.html"><svg viewBox="0 0 24 24"><polyline points="15 18 9 12 15 6"/></svg> Terug naar overzicht</a>\n'
        f'      <span class="hero-badge">{esc(para_number)} &middot; Samenvatting</span>\n'
        f'      <h1>{esc(para_name)} &mdash; Samenvatting</h1>\n'
        f'      <p class="hero-sub">{esc(data["subtitle"])}</p>\n'
        '      <div class="hero-actions">\n'
        f'        <a class="hero-action" href="{esc(docx_filename)}" download>Download als Word</a>\n'
        '      </div>\n'
        '    </div>\n'
        '  </header>\n'
    )

    # Sidebar nav: one entry per cell.
    sidebar_items = []
    for sec in data['sections']:
        sidebar_items.append(
            f'        <a class="nav-item" href="#cel-{sec["index"]}">'
            f'<span class="nav-num">{sec["index"]}</span>'
            f'<span class="nav-title">{esc(sec["heading"]) or "(zonder titel)"}</span>'
            f'<span class="nav-badge badge-{sec["shared_domain"]}">{esc(sec["domain"])}</span></a>'
        )
    sidebar = (
        '  <nav class="sidebar" id="sidebar">\n'
        '    <div class="sidebar-header">\n'
        f'      <h2>{esc(para_number)} {esc(para_name)}</h2>\n'
        '      <p>Samenvatting</p>\n'
        '    </div>\n'
        + '\n'.join(sidebar_items) + '\n'
        '  </nav>\n'
    )

    # Sections grid.
    section_blocks = []
    for sec in data['sections']:
        body = render_section_body(sec, asset_prefix, web_variant_bases)
        section_blocks.append(
            f'      <section class="samenvatting-cell domain-{sec["shared_domain"]}" id="cel-{sec["index"]}">\n'
            f'        <header class="cell-header">\n'
            f'          <span class="cell-num">{sec["index"]}</span>\n'
            f'          <h2 class="cell-title">{esc(sec["heading"]) or "(zonder titel)"}</h2>\n'
            f'          <span class="cell-badge badge-{sec["shared_domain"]}">{esc(sec["domain"])}</span>\n'
            f'        </header>\n'
            f'        <div class="cell-body">\n'
            f'{body}'
            f'        </div>\n'
            f'      </section>'
        )
    main_grid = '    <main class="samenvatting-grid">\n' + '\n'.join(section_blocks) + '\n    </main>\n'

    # Boot script for theme + prefers-color-scheme handling, mirroring
    # convert_voorkennis.py / convert_vaardigheden.py.
    boot_script = (
        '<script>\n'
        '(function(){try{var m=localStorage.getItem("quizMode");\n'
        'if(!m && window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches){m="dark";}\n'
        'if(m==="dark"){document.documentElement.setAttribute("data-theme","dark");}\n'
        '}catch(e){}})();\n'
        '</script>'
    )

    html_doc = f'''<!doctype html>
<html lang="nl" data-theme="light">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{esc(para_name)} &mdash; Samenvatting</title>
  <link rel="stylesheet" href="{shared_prefix}/voorkennis.css">
  {boot_script}
</head>
<body data-layout="samenvatting-v1" data-accent-domain="economisch">
<button class="sidebar-toggle" id="sidebarToggle" aria-label="Menu">&#9776;</button>
<div class="sidebarOverlay" id="sidebarOverlay"></div>
<div class="page-layout">
{sidebar}  <div class="content">
{hero}{main_grid}  </div>
</div>
<script src="{shared_prefix}/voorkennis.js"></script>
</body>
</html>
'''
    return html_doc


def find_paragraph_info(folder_path):
    """Extract paragraph number and name from folder path."""
    basename = os.path.basename(folder_path.rstrip('/\\'))
    parts = basename.split(' ', 1)
    number = parts[0]
    if ' - ' in basename:
        name = basename.split(' - ', 1)[1]
    else:
        name = parts[1] if len(parts) > 1 else basename
    return number, name


def process_paragraph(para_folder):
    """Process a single paragraph folder.

    Returns one of:
      'ok'    — html generated successfully
      'skip'  — no samenvatting.docx found, or the doc parsed to zero cells
      'error' — a parse/IO failure occurred; caller MUST surface as exit-1

    The 'skip' vs 'error' distinction is load-bearing for the deploy
    pipeline: skip is "this paragraph doesn't carry this content type yet,
    that's fine"; error is "the input is malformed, fail loudly". Earlier
    versions returned False for both, which made deploy.js silently count
    parse failures as OK.
    """
    para_number, para_name = find_paragraph_info(para_folder)
    pattern = os.path.join(para_folder, '*samenvatting*.docx')
    found = glob.glob(pattern)
    if not found:
        print(f'  SKIP {para_number}: no samenvatting.docx found')
        return 'skip'
    docx_path = found[0]

    asset_prefix = '_assets'
    shared_prefix = '../../shared'

    try:
        data = build_data_from_doc(docx_path, para_number, para_name)
    except Exception as e:
        print(f'  ERROR {para_number}: {e}')
        return 'error'

    if not data['sections']:
        print(f'  SKIP {para_number}: no cells found in samenvatting.docx')
        return 'skip'

    web_variant_bases = find_web_variant_bases(os.path.join(para_folder, '_assets'))

    try:
        html_content = generate_html(
            data, para_number, para_name,
            asset_prefix=asset_prefix,
            shared_prefix=shared_prefix,
            web_variant_bases=web_variant_bases,
        )
        html_path = os.path.join(para_folder, f'{para_number} {para_name} – samenvatting.html')
        with open(html_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
    except Exception as e:
        print(f'  ERROR {para_number}: {e}')
        return 'error'

    n_assets = sum(1 for s in data['sections'] for _ in s['assets'])
    print(f'  OK {para_number} {para_name} ({len(data["sections"])} cells, {n_assets} assets)')
    return 'ok'


def main():
    args = sys.argv[1:]
    if len(args) < 1:
        print('Usage: python convert_samenvatting.py [path] or --all')
        sys.exit(1)

    had_error = False
    if args[0] == '--all':
        # Walk Boek N directories beside the platform root.
        base = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        # base points at /c/Projects/4veco/4veco-platform-d1d2; siblings are 4veco-lessen/Boek*/etc.
        siblings_root = os.path.dirname(base)
        folders = []
        for boek in sorted(glob.glob(os.path.join(siblings_root, '4veco-lessen', 'Boek*'))):
            for chap in sorted(glob.glob(os.path.join(boek, '*'))):
                if not os.path.isdir(chap):
                    continue
                for para in sorted(glob.glob(os.path.join(chap, '*'))):
                    if os.path.isdir(para):
                        folders.append(para)
        # Also walk 3.* layout for legacy paragraphs.
        for f in sorted(glob.glob(os.path.join(base, '3.*/3.*.*'))):
            folders.append(f)
        print(f'Found {len(folders)} candidate paragraph folders')
        success = 0
        for folder in folders:
            result = process_paragraph(folder)
            if result == 'ok':
                success += 1
            elif result == 'error':
                had_error = True
        print(f'\nDone: {success}/{len(folders)} converted')
    else:
        result = process_paragraph(args[0])
        if result == 'error':
            had_error = True

    sys.exit(1 if had_error else 0)


if __name__ == '__main__':
    main()
