#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Convert 'nieuws met visual.docx' to a self-contained sibling HTML page.

Usage: python convert_nieuws.py [paragraph_folder_path]
       python convert_nieuws.py --all   (processes all paragraphs)

HOW IT WORKS
============
The 'nieuws met visual' docx is generated by
build-scripts/content/book-1/b1-<para>-nieuws.js as a domain-banner
article: headline, embedded news visual, article body (multiple
paragraphs), source line ("Bron: ..."), then a Vragen banner table,
five questions (a..e), a page break, an Antwoordmodel banner table,
and five model answers (a..e).

This converter walks the docx body in document order, uses the two
banner tables as boundaries to split questions/answers cleanly, and
emits a sibling .html with the same web stack as convert_samenvatting.py
(body[data-layout="nieuws-v1"], shared voorkennis.css, light/dark image
swap, page-layout flex, sidebar nav).

The b1-111-nieuws.js builder embeds the news visual without a
'descr="asset:..."' alt-text, so the visual base name is detected via a
filename glob over _assets/*_news_*_web_light.svg. This is a known gap;
the builder should be patched separately to emit proper alt-text.

Note: the converter emits .nieuws-article / .nieuws-questions /
.nieuws-source / .nieuws-answers / .external-source hooks that are not
yet styled in engines/voorkennis.css. The page reuses .samenvatting-cell
for inherited boxing, so content reads correctly in this commit; a
follow-up CSS commit (D1-2b) will polish the news-specific surfaces.
"""
import sys, io, os, glob, html as html_mod, re
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')
from docx import Document
from docx.oxml.ns import qn

# Domain -> color mapping (copied from convert_samenvatting.py).
DOMAIN_MAP = {
    'Wiskundig':        ('wiskunde',   '#1A5276', '#EBF5FB', '#154360'),
    'Economisch':       ('economisch', '#E67E22', '#FEF5E7', '#BA6A1C'),
    'Grafisch':         ('grafisch',   '#1E8449', '#E8F8F0', '#186A3B'),
    'Bedrijfseconomie': ('bedrijf',    '#E67E22', '#FEF5E7', '#BA6A1C'),
    'Marktanalyse':     ('markt',      '#1A5276', '#EBF5FB', '#154360'),
    'Marktwerking':     ('marktwerk',  '#1A5276', '#EBF5FB', '#154360'),
    'Overheidsbeleid':  ('overheid',   '#1E8449', '#E8F8F0', '#186A3B'),
    'Arbeidsmarkt':     ('arbeids',    '#E67E22', '#FEF5E7', '#BA6A1C'),
    'Externe effecten': ('extern',     '#1E8449', '#E8F8F0', '#186A3B'),
}

SHARED_DOMAIN_TOKENS = {
    'wiskunde':   'wiskunde',
    'economisch': 'economisch',
    'grafisch':   'grafisch',
    'bedrijf':    'economisch',
    'markt':      'wiskunde',
    'marktwerk':  'wiskunde',
    'overheid':   'grafisch',
    'arbeids':    'economisch',
    'extern':     'grafisch',
}

# Per b1-111-nieuws.js the news doc carries the markt domain (blue),
# which collapses to wiskunde via SHARED_DOMAIN_TOKENS. For paragraphs
# whose news-doc builder picks a different domain, override here.
NIEUWS_DOMAIN = 'Marktanalyse'


def get_domain_info(domain_name):
    if domain_name in DOMAIN_MAP:
        return DOMAIN_MAP[domain_name]
    slug = domain_name.lower().replace(' ', '')[:8]
    return (slug, '#1A5276', '#EBF5FB', '#154360')


def shared_domain_class(domain_name):
    slug = get_domain_info(domain_name)[0]
    return SHARED_DOMAIN_TOKENS.get(slug, 'economisch')


def esc(text):
    return html_mod.escape(text)


def find_web_variant_bases(assets_dir):
    bases = set()
    if os.path.isdir(assets_dir):
        for svg in glob.glob(os.path.join(assets_dir, '*_web_light.svg')):
            base = os.path.basename(svg).replace('_web_light.svg', '')
            if os.path.exists(os.path.join(assets_dir, base + '_web_dark.svg')):
                bases.add(base)
    return bases


def find_news_visual_base(assets_dir):
    """Fallback: locate the news visual asset base via filename glob.
    Used only when the docx itself doesn't carry alt-text metadata
    (legacy builders). Filename convention: <para>_news_<topic>_web_light.svg.
    Post-L1.5V Bucket A4 the builder emits asset-alt:<text> in the
    image's docPr descr, so this fallback is rarely hit on §1.1.1."""
    if not os.path.isdir(assets_dir):
        return None
    matches = sorted(glob.glob(os.path.join(assets_dir, '*_news_*_web_light.svg')))
    if not matches:
        return None
    return os.path.basename(matches[0]).replace('_web_light.svg', '')


def extract_news_visual_from_docx(doc):
    """L1.5V Bucket A4 + post-PR-review fix: read the news visual's alt-text
    out of the docx image's wp:docPr metadata. Returns
    {'base': str, 'alt': str} when the builder emitted asset-alt:<text>
    (canonical post-A4); returns {'base': str, 'alt': str-fallback} when
    only the legacy asset:<id> prefix is present and warns to stderr;
    returns None when no embedded image carries either prefix."""
    for p in doc.paragraphs:
        for run in p.runs:
            blips = run._element.findall('.//' + qn('a:blip'))
            if not blips:
                continue
            drawing = run._element.find('.//' + qn('wp:inline'))
            if drawing is None:
                continue
            docPr = drawing.find(qn('wp:docPr'))
            if docPr is None:
                continue
            descr = docPr.get('descr', '') or ''
            title = docPr.get('title', '') or ''
            if descr.startswith('asset-alt:'):
                alt = descr[len('asset-alt:'):]
                base = title or alt[:30]
                return {'base': base, 'alt': alt}
            if descr.startswith('asset:'):
                base = descr[len('asset:'):]
                sys.stderr.write(
                    f"WARNING: legacy 'asset:' prefix for {base!r} in nieuws "
                    f"(migrate builder to pass altText).\n"
                )
                return {'base': base, 'alt': base}
    return None


def render_asset_image(asset_prefix, payload, web_variant_bases):
    """L1.5V Bucket A4 + post-PR-review: payload is now
    {'base': str, 'alt': str} (or a bare asset id for the legacy filename-
    glob fallback). `base` selects the SVG variant; `alt` becomes the
    rendered <img alt>."""
    if isinstance(payload, dict):
        base = payload['base']
        alt = payload['alt']
    else:
        base = payload
        alt = payload
    if base in web_variant_bases:
        light_src = f'{asset_prefix}/{esc(base)}_web_light.svg'
        dark_src = f'{asset_prefix}/{esc(base)}_web_dark.svg'
        fallback_src = f'{asset_prefix}/{esc(base)}.svg'
        return (
            '        <figure class="asset-figure">\n'
            f'          <img src="{light_src}" data-light-src="{light_src}" '
            f'data-dark-src="{dark_src}" data-fallback-src="{fallback_src}" '
            f'alt="{esc(alt)}" class="asset-svg">\n'
            '        </figure>\n'
        )
    return (
        '        <figure class="asset-figure">\n'
        f'          <img src="{asset_prefix}/{esc(base)}.svg" '
        f'alt="{esc(alt)}" class="asset-svg">\n'
        '        </figure>\n'
    )


SOURCE_PATTERN = re.compile(r'^Bron\s*:', re.IGNORECASE)
LETTER_PREFIX = re.compile(r'^([a-h])\)\s+(.*)$', re.DOTALL)
URL_PATTERN = re.compile(r'(https?://\S+)')


def parse_document(docx_path):
    """Walk the body in document order, partitioning paragraphs by their
    position relative to the Vragen (T0) and Antwoordmodel (T1) banner
    tables. Returns a dict: headline / article / source / questions /
    answers."""
    doc = Document(docx_path)
    body_children = list(doc.element.body)

    # Map document-order indices to either a 'p' position or a 'tbl' position.
    table_body_positions = []
    para_objects = list(doc.paragraphs)
    para_iter = iter(enumerate(para_objects))
    para_at_body_pos = {}
    table_idx = 0
    para_idx_pointer = 0
    for body_pos, child in enumerate(body_children):
        tag = child.tag.split('}')[-1] if '}' in child.tag else child.tag
        if tag == 'p':
            if para_idx_pointer < len(para_objects):
                para_at_body_pos[body_pos] = para_objects[para_idx_pointer]
                para_idx_pointer += 1
        elif tag == 'tbl':
            table_body_positions.append(body_pos)
            table_idx += 1

    # Sentinel banner positions; use +inf if missing.
    t0_pos = table_body_positions[0] if len(table_body_positions) >= 1 else 10**9
    t1_pos = table_body_positions[1] if len(table_body_positions) >= 2 else 10**9

    headline = ''
    article = []
    source_text = ''
    source_url = None
    questions = []
    answers = []

    # First non-empty paragraph before T0 is the headline. The next
    # paragraphs up to the source line form the article body. The source
    # line starts with 'Bron:'. Image-only paragraphs are skipped.
    for body_pos, p in para_at_body_pos.items():
        text = p.text.strip()
        # Skip image-only paragraphs (carry a blip but no text).
        is_image_only = (not text) and bool(p._element.findall('.//' + qn('a:blip')))
        if is_image_only:
            continue

        if body_pos < t0_pos:
            # Article zone (before Vragen banner).
            if not text:
                continue
            if SOURCE_PATTERN.match(text):
                source_text = text
                m = URL_PATTERN.search(text)
                if m:
                    source_url = m.group(1)
                continue
            if not headline:
                headline = text
            else:
                article.append(text)
        elif t0_pos < body_pos < t1_pos:
            # Questions zone.
            m = LETTER_PREFIX.match(text)
            if m:
                questions.append(m.group(2).strip())
        elif body_pos > t1_pos:
            # Answers zone.
            m = LETTER_PREFIX.match(text)
            if m:
                answers.append(m.group(2).strip())

    return {
        'headline': headline,
        'article': article,
        'source_text': source_text,
        'source_url': source_url,
        'questions': questions,
        'answers': answers,
    }


def build_data_from_doc(docx_path, para_number, para_name, assets_dir):
    parsed = parse_document(docx_path)
    domain = NIEUWS_DOMAIN

    # L1.5V Bucket A4 + post-PR-review: prefer the docx's embedded alt-text
    # metadata over the filename-glob fallback. The visual payload is now
    # a {'base': str, 'alt': str} dict so render_asset_image() can emit
    # meaningful HTML alt text. Filename glob only fires when the docx has
    # no asset-* descr at all (paragraphs that haven't migrated yet).
    visual_payload = extract_news_visual_from_docx(Document(docx_path))
    if visual_payload is None:
        fallback_base = find_news_visual_base(assets_dir)
        if fallback_base is None:
            visual_payload = None
        else:
            visual_payload = {'base': fallback_base, 'alt': fallback_base}
            sys.stderr.write(
                f"WARNING: nieuws visual alt-text missing in {os.path.basename(docx_path)} "
                f"— falling back to filename-glob asset id {fallback_base!r}. "
                f"Migrate b1-XXX-nieuws.js to pass altText.\n"
            )

    return {
        'number': para_number,
        'title': para_name,
        'domain': domain,
        'shared_domain': shared_domain_class(domain),
        'visual_payload': visual_payload,
        # Legacy alias kept for any consumer that still reads visual_base —
        # may be removed in a future sprint.
        'visual_base': visual_payload['base'] if visual_payload else None,
        **parsed,
    }


def render_questions_list(items):
    parts = ['        <ol class="nieuws-q-list">']
    for q in items:
        parts.append(f'          <li>{esc(q)}</li>')
    parts.append('        </ol>')
    return '\n'.join(parts) + '\n'


def render_article_html(data, asset_prefix, web_variant_bases):
    parts = []
    if data.get('visual_payload'):
        parts.append(render_asset_image(asset_prefix, data['visual_payload'], web_variant_bases))
    for para in data['article']:
        parts.append(f'        <p class="cell-para">{esc(para)}</p>')
    if data['source_text']:
        if data['source_url']:
            label = data['source_text'].replace(data['source_url'], '').strip().rstrip('—').strip()
            if not label:
                label = data['source_url']
            parts.append(
                f'        <p class="nieuws-source">'
                f'<a class="external-source" href="{esc(data["source_url"])}" target="_blank" rel="noopener">'
                f'{esc(label)}</a></p>'
            )
        else:
            parts.append(f'        <p class="nieuws-source">{esc(data["source_text"])}</p>')
    return '\n'.join(parts) + '\n' if parts else ''


def generate_html(data, para_number, para_name, asset_prefix='_assets',
                  shared_prefix=None, web_variant_bases=None):
    if web_variant_bases is None:
        web_variant_bases = set()
    if not shared_prefix:
        shared_prefix = '../../shared'

    docx_filename = f'{para_number} {para_name} – nieuws met visual.docx'
    accent_domain = get_domain_info(data['domain'])[0]
    shared_class = data['shared_domain']

    hero = (
        '  <header class="hero">\n'
        '    <div class="hero-inner">\n'
        '      <a class="back-link" href="../index.html"><svg viewBox="0 0 24 24"><polyline points="15 18 9 12 15 6"/></svg> Terug naar overzicht</a>\n'
        f'      <span class="hero-badge">{esc(para_number)} &middot; Nieuws met visual</span>\n'
        f'      <h1>{esc(para_name)} &mdash; Nieuws met visual</h1>\n'
        f'      <p class="hero-sub">{esc(data["headline"])}</p>\n'
        '      <div class="hero-actions">\n'
        f'        <a class="hero-action" href="{esc(docx_filename)}" download>Download als Word</a>\n'
        '      </div>\n'
        '    </div>\n'
        '  </header>\n'
    )

    sidebar_items = [
        f'        <a class="nav-item" href="#artikel">'
        f'<span class="nav-num">1</span>'
        f'<span class="nav-title">Artikel</span>'
        f'<span class="nav-badge badge-{shared_class}">{esc(data["domain"])}</span></a>',
        f'        <a class="nav-item" href="#vragen">'
        f'<span class="nav-num">2</span>'
        f'<span class="nav-title">Vragen</span>'
        f'<span class="nav-badge badge-{shared_class}">{esc(data["domain"])}</span></a>',
        f'        <a class="nav-item" href="#antwoorden">'
        f'<span class="nav-num">3</span>'
        f'<span class="nav-title">Antwoordmodel</span>'
        f'<span class="nav-badge badge-{shared_class}">{esc(data["domain"])}</span></a>',
    ]
    sidebar = (
        '  <nav class="sidebar" id="sidebar">\n'
        '    <div class="sidebar-header">\n'
        f'      <h2>{esc(para_number)} {esc(para_name)}</h2>\n'
        '      <p>Nieuws met visual</p>\n'
        '    </div>\n'
        + '\n'.join(sidebar_items) + '\n'
        '  </nav>\n'
    )

    article_inner = render_article_html(data, asset_prefix, web_variant_bases)
    article_section = (
        f'      <section id="artikel" class="nieuws-article samenvatting-cell domain-{shared_class}">\n'
        f'        <header class="cell-header">\n'
        f'          <span class="cell-num">1</span>\n'
        f'          <h2 class="cell-title">{esc(data["headline"])}</h2>\n'
        f'          <span class="cell-badge badge-{shared_class}">{esc(data["domain"])}</span>\n'
        f'        </header>\n'
        f'        <div class="cell-body">\n'
        f'{article_inner}'
        f'        </div>\n'
        f'      </section>'
    )

    questions_inner = render_questions_list(data['questions']) if data['questions'] else ''
    questions_section = (
        f'      <section id="vragen" class="nieuws-questions samenvatting-cell domain-{shared_class}">\n'
        f'        <header class="cell-header">\n'
        f'          <span class="cell-num">2</span>\n'
        f'          <h2 class="cell-title">Vragen</h2>\n'
        f'          <span class="cell-badge badge-{shared_class}">{esc(data["domain"])}</span>\n'
        f'        </header>\n'
        f'        <div class="cell-body">\n'
        f'{questions_inner}'
        f'        </div>\n'
        f'      </section>'
    )

    answers_inner = render_questions_list(data['answers']) if data['answers'] else ''
    answers_section = (
        f'      <details id="antwoorden" class="nieuws-answers samenvatting-cell domain-{shared_class}">\n'
        f'        <summary>Antwoordmodel tonen</summary>\n'
        f'        <div class="cell-body">\n'
        f'{answers_inner}'
        f'        </div>\n'
        f'      </details>'
    )

    main_grid = (
        '    <main class="nieuws-grid">\n'
        + article_section + '\n'
        + questions_section + '\n'
        + answers_section + '\n'
        '    </main>\n'
    )

    boot_script = (
        '<script>\n'
        '(function(){try{var m=localStorage.getItem("quizMode");\n'
        'if(!m && window.matchMedia && window.matchMedia("(prefers-color-scheme: dark)").matches){m="dark";}\n'
        'if(m==="dark"){document.documentElement.setAttribute("data-theme","dark");}\n'
        '}catch(e){}})();\n'
        '</script>'
    )

    html_doc = f'''<!doctype html>
<html lang="nl" data-theme="light">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{esc(para_name)} &mdash; Nieuws met visual</title>
  <link rel="stylesheet" href="{shared_prefix}/voorkennis.css">
  {boot_script}
</head>
<body data-layout="nieuws-v1" data-accent-domain="{accent_domain}">
<button class="sidebar-toggle" id="sidebarToggle" aria-label="Menu">&#9776;</button>
<div class="sidebarOverlay" id="sidebarOverlay"></div>
<div class="page-layout">
{sidebar}  <div class="content">
{hero}{main_grid}  </div>
</div>
<script src="{shared_prefix}/voorkennis.js"></script>
</body>
</html>
'''
    return html_doc


def find_paragraph_info(folder_path):
    basename = os.path.basename(folder_path.rstrip('/\\'))
    parts = basename.split(' ', 1)
    number = parts[0]
    if ' - ' in basename:
        name = basename.split(' - ', 1)[1]
    else:
        name = parts[1] if len(parts) > 1 else basename
    return number, name


def process_paragraph(para_folder):
    """Process a single paragraph folder.

    Returns one of:
      'ok'    — html generated successfully
      'skip'  — no nieuws-met-visual.docx found, or no headline parsed
      'error' — a parse/IO failure occurred; caller MUST surface as exit-1

    The 'skip' vs 'error' distinction is load-bearing: skip means "this
    paragraph doesn't carry this content type yet"; error means "the input
    is malformed". Earlier versions returned False for both, which made
    deploy.js silently count parse failures as OK.
    """
    para_number, para_name = find_paragraph_info(para_folder)
    pattern = os.path.join(para_folder, '*nieuws met visual*.docx')
    found = glob.glob(pattern)
    if not found:
        print(f'  SKIP {para_number}: no nieuws-met-visual docx found')
        return 'skip'
    docx_path = found[0]

    asset_prefix = '_assets'
    shared_prefix = '../../shared'
    assets_dir = os.path.join(para_folder, '_assets')

    try:
        data = build_data_from_doc(docx_path, para_number, para_name, assets_dir)
    except Exception as e:
        print(f'  ERROR {para_number}: {e}')
        return 'error'

    if not data['headline']:
        print(f'  SKIP {para_number}: no headline parsed from nieuws docx')
        return 'skip'

    web_variant_bases = find_web_variant_bases(assets_dir)

    try:
        html_content = generate_html(
            data, para_number, para_name,
            asset_prefix=asset_prefix,
            shared_prefix=shared_prefix,
            web_variant_bases=web_variant_bases,
        )
        html_path = os.path.join(para_folder, f'{para_number} {para_name} – nieuws met visual.html')
        with open(html_path, 'w', encoding='utf-8') as f:
            f.write(html_content)
    except Exception as e:
        print(f'  ERROR {para_number}: {e}')
        return 'error'

    asset_label = data['visual_base'] or 'none'
    print(f'  OK {para_number} {para_name} ({len(data["questions"])} vragen, '
          f'{len(data["answers"])} antwoorden, asset={asset_label})')
    return 'ok'


def main():
    args = sys.argv[1:]
    if len(args) < 1:
        print('Usage: python convert_nieuws.py [path] or --all')
        sys.exit(1)

    had_error = False
    if args[0] == '--all':
        base = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
        siblings_root = os.path.dirname(base)
        folders = []
        for boek in sorted(glob.glob(os.path.join(siblings_root, '4veco-lessen', 'Boek*'))):
            for chap in sorted(glob.glob(os.path.join(boek, '*'))):
                if not os.path.isdir(chap):
                    continue
                for para in sorted(glob.glob(os.path.join(chap, '*'))):
                    if os.path.isdir(para):
                        folders.append(para)
        print(f'Found {len(folders)} candidate paragraph folders')
        success = 0
        for folder in folders:
            result = process_paragraph(folder)
            if result == 'ok':
                success += 1
            elif result == 'error':
                had_error = True
        print(f'\nDone: {success}/{len(folders)} converted')
    else:
        result = process_paragraph(args[0])
        if result == 'error':
            had_error = True

    sys.exit(1 if had_error else 0)


if __name__ == '__main__':
    main()
