"""Own §212 S1 evidence driver; immutable outputs, no acceptance decisions.

HOW TO ADAPT: commission a new exact-pair work order; do not rewrite checkpoints.
Runs native builders in separate processes. Never restores generated bytes.
"""
from pathlib import Path
import argparse
import datetime
import hashlib
import json
import os
import re
import subprocess
import sys
from zipfile import ZipFile

ROOT = Path(__file__).resolve().parents[2]
LESSONS = ROOT.parent / '4veco-lessen'
REL = Path('Boek 2 - Kosten, opbrengsten, elasticiteit en surplus/2.1 Hoofdstuk Kosten en opbrengsten/2.1.2 Opbrengsten, winst en break-even')
FOLDER = LESSONS / REL
STEM = '2.1.2 Opbrengsten, winst en break-even'
PREFIX = 'BOOK2-TEXTBOOK-PRODUCTION-1-212-S1'
OUT = ROOT / 'reports/sprints' / (PREFIX + '-evidence')
PROOF = OUT / 'proofs'
R9 = ROOT / 'reports/sprints/BOOK2-TEXTBOOK-PRODUCTION-1-212-R7-REVIEW-evidence'
PROOF_COMPONENT = re.compile(r'^212-.+-r([1-9][0-9]*)$')
PBASE = '572d1ea2ededaffd28afc44eeeca223252a58ec5'
LBASE = 'd4e1910d60964ee4b9ac97eefbf0e0ed202fc28f'
PYTHON = 'C:/Python314/python.exe'
KINDS = ('paragraaf', 'opgaven', 'antwoorden')
NATIVE = [f'{STEM} – {kind}.{ext}' for kind in KINDS for ext in ('md','html','pdf','zip')] + [f'_assets/2.1.2_{role}_{n}.{ext}' for role, numbers in [('fig',range(1,5)),('we',range(1,2)),('ex',range(1,7))] for n in numbers for ext in ('svg','png')]


def sha(value):
    return hashlib.sha256(value).hexdigest()


def save(name, value):
    OUT.mkdir(exist_ok=True)
    with (OUT / name).open('x', encoding='utf-8', newline='\n') as stream:
        stream.write(json.dumps(value, ensure_ascii=False, indent=2) + '\n')


def command(argv, name, cwd=ROOT):
    start = datetime.datetime.now(datetime.timezone.utc).isoformat()
    run = subprocess.run(list(map(str,argv)), cwd=cwd, capture_output=True)
    result = dict(argv=list(map(str,argv)), cwd=str(cwd), started_at=start,
                  finished_at=datetime.datetime.now(datetime.timezone.utc).isoformat(),
                  exit_code=run.returncode, stdout=run.stdout.decode('utf-8',errors='replace'),
                  stderr=run.stderr.decode('utf-8',errors='replace'),
                  stdout_sha256=sha(run.stdout), stderr_sha256=sha(run.stderr))
    save(name, result)
    print(name, 'exit', run.returncode, flush=True)
    if run.returncode:
        raise RuntimeError(f'{name}: native exit {run.returncode}; complete output preserved')
    return result


def native():
    assert len(NATIVE) == len(set(NATIVE)) == 34
    return {name: sha((FOLDER/name).read_bytes()) for name in NATIVE}


def archives():
    result = {}
    for kind, count in zip(KINDS,(19,11,9)):
        with ZipFile(FOLDER / f'{STEM} – {kind}.zip') as archive:
            assert len(archive.namelist()) == len(set(archive.namelist())) == count
            assert archive.testzip() is None
            members = []
            for item in archive.infolist():
                data = archive.read(item.filename)
                assert data == (FOLDER/item.filename).read_bytes()
                members.append(dict(name=item.filename, crc=item.CRC, size=item.file_size,
                                    sha256=sha(data), date_time=list(item.date_time)))
            result[kind] = members
    return result


def protected():
    pfiles = ['build-scripts/content/book-2/print_pipeline.py',
              'references/authored/course-target-exercises.json',
              'references/authored/book-outlines/book-2-outline.md',
              'references/authored/book-outlines/book-2-outline.meta.json',
              'reports/sprints/BOOK2-TEXTBOOK-PRODUCTION-1-successor-binding-plan.md',
              'reports/sprints/BOOK2-TEXTBOOK-PRODUCTION-1-successor-binding-r2-independent-review.md']
    pfiles += [p.relative_to(ROOT).as_posix() for p in (ROOT/'build-scripts/content/book-2/212').iterdir()
               if p.is_file() and p.name != 'test_metadata.py' and p.name != 'test_succession.py']
    lfiles = [p.relative_to(LESSONS).as_posix() for p in FOLDER.iterdir()
              if p.is_file() and p.name not in NATIVE]
    lfiles += [(REL.parent/'2.1.1 Kostenstructuren'/name).as_posix() for name in
               ('2.1.1-review.md','2.1.1-quality-ref.yaml','2.1.1-textbook-handoff.md')]
    lfiles += [(REL.parent/'_chapter-plan.md').as_posix(), (REL.parent.parent/'_book-plan.md').as_posix()]
    return {**{'platform/'+p:sha((ROOT/p).read_bytes()) for p in pfiles},
            **{'lessons/'+p:sha((LESSONS/p).read_bytes()) for p in lfiles}}


def old_proofs():
    historical_root = ROOT / 'reports/rendered-proof/BOOK2-TEXTBOOK-PRODUCTION-1'
    return {p.relative_to(ROOT).as_posix():sha(p.read_bytes()) for d in historical_root.glob('212-*-r*')
            for p in d.rglob('*') if p.is_file()}


def supplement():
    """Bind every inherited proof path to immutable Git; do not replace baseline."""
    listing = subprocess.check_output(['git','ls-tree','-rz','--full-tree',PBASE,'reports'],cwd=ROOT)
    result = {}
    for entry in listing.split(b'\0'):
        if not entry:
            continue
        meta, encoded = entry.split(b'\t',1)
        name = encoded.decode('utf-8')
        if not any(PROOF_COMPONENT.fullmatch(part) for part in Path(name).parts):
            continue
        blob = subprocess.check_output(['git','cat-file','blob',meta.split()[2].decode()],cwd=ROOT)
        raw = (ROOT/name).read_bytes()
        comparable = raw.replace(b'\r\n',b'\n') if Path(name).suffix in ('.json','.md','.txt') else raw
        assert comparable == blob, ('Inherited proof differs from PBASE',name)
        result[name] = dict(raw_sha256=sha(raw), git_blob_sha256=sha(blob))
    assert result and any('-r9/' in name for name in result)
    save('inherited-proof-supplement.json',dict(platform_base=PBASE, files=result,
         reason='Initial snapshot covered standard root only; this supplement binds all inherited nested proofs directly to immutable PBASE, after diagnostic r7 and before valid succession reproduction.'))
    print(f'Immutable PBASE supplemental proof binding: {len(result)} files.')


def snapshot():
    assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=LESSONS).decode().strip() == LBASE
    assert subprocess.check_output(['git','status','--porcelain'],cwd=LESSONS) == b''
    save('baseline.json', dict(platform_base=PBASE, lesson_base=LBASE,
         raw_native=native(), archives=archives(), protected=protected(), old_proofs=old_proofs(),
         generator_raw=sha((ROOT/'build-scripts/content/book-2/b2_212.py').read_bytes()),
         metadata_raw=sha((ROOT/'build-scripts/content/book-2/212/test_metadata.py').read_bytes()),
         interpreter=PYTHON, inherited_path=os.environ.get('PATH','')))
    print('Baseline:34 native, all archive members, protected inputs and old212 proof files captured.')


def check_baseline():
    base=json.loads((OUT/'baseline.json').read_text(encoding='utf-8'))
    assert native() == base['raw_native'], 'Native bytes changed; do not restore them'
    assert archives() == base['archives'], 'Archive member/CRC drift'
    assert protected() == base['protected'], 'Protected source/metadata drift'
    for name,value in base['old_proofs'].items():
        assert sha((ROOT/name).read_bytes()) == value, ('Old proof changed',name)
    supplemental=OUT/'inherited-proof-supplement.json'
    if supplemental.exists():
        for name,value in json.loads(supplemental.read_text(encoding='utf-8'))['files'].items():
            assert sha((ROOT/name).read_bytes()) == value['raw_sha256'], ('Inherited proof changed',name)
    return base


def next_revision():
    worktrees=subprocess.check_output(['git','worktree','list','--porcelain'],cwd=ROOT).decode('utf-8').splitlines()
    used=[]
    for line in worktrees:
        if not line.startswith('worktree '):
            continue
        path=Path(line[9:])/'reports'
        if path.is_dir():
            for directory, children, files in os.walk(path):
                for name in children:
                    match=PROOF_COMPONENT.fullmatch(name)
                    if match:
                        used.append(dict(path=str(Path(directory)/name), revision=int(match[1]), kind='proof_directory'))
                for name in files:
                    candidate=Path(directory)/name
                    if '212' in str(candidate) and re.search(r'(attempt|reserv)',name,re.I):
                        matches=re.findall(r'(?:^|[-_])r([1-9][0-9]*)(?=[-_.]|$)',name)
                        if not matches and candidate.suffix=='.json':
                            matches=re.findall(r'"(?:revision|proof_suffix|suffix)"\s*:\s*"r([1-9][0-9]*)"',candidate.read_text(encoding='utf-8'))
                        for number in matches:
                            used.append(dict(path=str(candidate), revision=int(number), kind='reservation_or_attempt'))
    local_attempts=list(OUT.glob('attempt-r*.json'))
    numbers=[int(re.search(r'r(\d+)',p.name)[1]) for p in local_attempts]+[row['revision'] for row in used]
    number=max(numbers, default=0)+1
    revision=f'r{number}'
    save('attempt-'+revision+'.json',dict(state='ATTEMPT_RECORDED', revision=revision,
        existing_registered_worktree_proofs=used, python=PYTHON, path=os.environ.get('PATH','')))
    return revision


def compare_pages(manifest):
    from PIL import Image, ImageChops
    comparisons=[]
    for kind,doc,count in zip(KINDS,manifest['documents'],(14,7,6)):
        new_dir=Path(doc['proof_directory'])
        old_dir=R9/f"212-{kind}-{doc['pdf_sha256'][:12]}-r9"
        previous=json.loads((old_dir/'manifest.json').read_text(encoding='utf-8'))
        current=json.loads((new_dir/'manifest.json').read_text(encoding='utf-8'))
        assert previous['inspection_status'] == current['inspection_status'] == 'PENDING'
        before=sorted((old_dir/'pages').glob('page-*.png'))
        after=sorted((new_dir/'pages').glob('page-*.png'))
        assert len(before)==len(after)==count
        for old,new in zip(before,after):
            assert old.read_bytes()==new.read_bytes(), (kind,new.name,'PNG bytes differ')
            with Image.open(old) as a,Image.open(new) as z:
                assert a.size == z.size
                assert ImageChops.difference(a.convert('RGB'),z.convert('RGB')).getbbox() is None
            comparisons.append(dict(kind=kind,old=old.relative_to(ROOT).as_posix(),
                current=new.relative_to(ROOT).as_posix(),sha256=sha(new.read_bytes()),pixel_delta=None))
    assert len(comparisons)==27
    return comparisons


def build_mode(mode):
    check_baseline()
    assert (OUT/'inherited-proof-supplement.json').is_file()
    revision=next_revision()
    for kind in KINDS:
        assert not list(PROOF.glob(f'212-{kind}-*-{revision}')), 'Proof destination already exists'
    manifest=OUT/f'{mode}-{revision}-build.json'
    assert not manifest.exists()
    if mode=='print':
        command([PYTHON,__file__,'print-worker','--revision',revision,'--manifest',manifest],
                f'{mode}-{revision}-command.json')
    else:
        builder=ROOT/'build-scripts/content/book-2/b2_212.py' if mode=='full' else FOLDER/'build_pdf.py'
        argv=[PYTHON,builder,'--proof-root',PROOF,'--proof-suffix',revision,'--manifest',manifest]
        if mode=='full':
            argv += ['--lesson-root',LESSONS]
        command(argv,f'{mode}-{revision}-command.json')
    current=json.loads(manifest.read_text(encoding='utf-8'))
    assert current['inspection_status']=='PENDING'
    check_baseline()
    result=dict(result='PASS',mode=mode,revision=revision,build_manifest=manifest.relative_to(ROOT).as_posix(),
                build_manifest_sha256=sha(manifest.read_bytes()),raw_native=native(),archives=archives(),
                pages=compare_pages(current),protected_unchanged=True,old_proofs_unchanged=True,
                independent_acceptance=False)
    save(f'{mode}-{revision}-reproduction.json',result)
    print(f'{mode} {revision}:34 raw-identical native files, ZIP19/11/9,27 byte/pixel-identical pages.')


def print_worker(revision,manifest):
    sys.path.insert(0,str(ROOT/'build-scripts/content/book-2'))
    import b2_212 as b
    records=[]
    for kind in KINDS:
        record=b.build_document(FOLDER/f'{STEM} – {kind}.md')
        record['zip']=b.zip_document(record)
        directory=PROOF/f"212-{kind}-{record['pdf_sha256'][:12]}-{revision}"
        b.render_proof(record,directory)
        record['proof_directory']=str(directory)
        records.append(record)
    with Path(manifest).open('x',encoding='utf-8',newline='\n') as stream:
        stream.write(json.dumps(dict(inspection_status='PENDING',documents=records),ensure_ascii=False,indent=2)+'\n')


def validate():
    check_baseline()
    jobs=[('focused-tests',[PYTHON,'-m','unittest','discover','-s','build-scripts/content/book-2/212','-p','test_*.py','-v']),
          ('native-checker',[PYTHON,'build-scripts/content/book-2/212/check_render.py']),
          ('student-web',['node','scripts/validate-paragraph.js','--mode','part-a','--profile','student-web',FOLDER]),
          ('publisher-print',['node','scripts/validate-paragraph.js','--mode','part-a','--profile','publisher-print',FOLDER]),
          ('currentness',['node','build-scripts/workflows/check-book-outline-currentness.js','--require-approved','--action','paragraph_production','--paragraph','2.1.2']),
          ('durable-authority',['node','build-scripts/workflows/check-book2-target-authority-remediation.js','--durable']),
          ('active-bundle',['node','build-scripts/sprints/check-sprint-bundle.js','BOOK2-TEXTBOOK-PRODUCTION-1'])]
    for name,argv in jobs:
        command(argv,'validation-'+name+'.json')
    check_baseline()
    print('Focused tests, native checker, both Part A profiles, currentness, durable authority and active bundle PASS. Not independent acceptance.')


def audit(name, head=None):
    check_baseline()
    assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=LESSONS).decode().strip()==LBASE
    assert subprocess.check_output(['git','status','--porcelain'],cwd=LESSONS)==b''
    args=['git','diff','--name-only','-z',PBASE]
    if head: args.append(head)
    paths=subprocess.check_output(args,cwd=ROOT).decode('utf-8').strip('\0').split('\0')
    if not head:
        paths+=subprocess.check_output(['git','ls-files','--others','--exclude-standard','-z'],cwd=ROOT).decode('utf-8').strip('\0').split('\0')
    paths=sorted(set(filter(None,paths)))
    source={'build-scripts/content/book-2/b2_212.py',
            'build-scripts/content/book-2/212/test_metadata.py',
            'build-scripts/content/book-2/212/test_succession.py'}
    diagnostic=['reports/rendered-proof/BOOK2-TEXTBOOK-PRODUCTION-1/'+stem+'/' for stem in
                ('212-paragraaf-e94d42f66ab9-r7','212-opgaven-94ebe5d35207-r7','212-antwoorden-d55f1da66723-r7')]
    allowed=lambda p:p in source or p.startswith('reports/sprints/'+PREFIX+'-') or any(p.startswith(d) for d in diagnostic)
    assert all(allowed(p) for p in paths), [p for p in paths if not allowed(p)]
    assert source.issubset(paths)
    command([PYTHON,'-m','unittest','discover','-s','build-scripts/content/book-2/212','-p','test_*.py','-v'],name+'-tests.json')
    save(name+'.json',dict(result='PASS',platform_base=PBASE,platform_head=head,
         lesson_head=LBASE,lesson_clean=True,changed_paths=paths,
         source_paths=sorted(source),protected_and_native_unchanged=True,
         no_independent_acceptance=True))
    print(name+': strict whole owned delta and all25 source/test guards PASS.')


if __name__=='__main__':
    parser=argparse.ArgumentParser()
    parser.add_argument('mode',choices=['snapshot','supplement','full','thin','print','print-worker','check','validate','audit'])
    parser.add_argument('--revision')
    parser.add_argument('--manifest')
    parser.add_argument('--name')
    parser.add_argument('--head')
    args=parser.parse_args()
    if args.mode=='snapshot': snapshot()
    elif args.mode=='supplement': supplement()
    elif args.mode=='validate': validate()
    elif args.mode=='audit': audit(args.name,args.head)
    elif args.mode=='print-worker': print_worker(args.revision,args.manifest)
    elif args.mode=='check':
        check_baseline(); print('All34 native/archives/protected/old proofs unchanged.')
    else: build_mode(args.mode)
