// HOW TO ADAPT: add reviewed moves to each repository's archive/relocations.json;
// generate this inventory through agent:index after staging intended paths.
const fs = require('fs');
const path = require('path');
const { loadRelocations, gitBlob } = require('../lib/historical-paths');

function buildArchiveIndex(repository, root, complete) {
  const relocations = loadRelocations(root);
  const files = [...new Set(Object.values(complete.groups).flat())]
    .filter(p => p.startsWith('archive/') && !['archive/README.md', 'archive/index.json', 'archive/index.md', 'archive/relocations.json', 'archive/cleanup-deletions.json'].includes(p));
  const entries = files.map(archivedPath => {
    const relocation = relocations.find(e => e.archived_path === archivedPath);
    const originalPath = relocation?.original_path || archivedPath;
    const sourceCommit = relocation?.source_commit || complete.source_commit;
    const finalBlob = gitBlob(fs.readFileSync(path.join(root, archivedPath)));
    if (relocation && finalBlob !== (relocation.final_blob || relocation.original_blob)) throw new Error(`Archive preservation mismatch: ${archivedPath}`);
    return {
      repository, original_path: originalPath, archived_path: archivedPath,
      original_blob: relocation?.original_blob || finalBlob, final_blob: finalBlob,
      source_commit: sourceCommit,
      original_url: `https://github.com/meijer1973/${repository}/blob/${sourceCommit}/${originalPath.split('/').map(encodeURIComponent).join('/')}`,
      topic: relocation?.topic || archivedPath.split('/')[2] || 'archive',
      current_consumers: relocation?.current_consumers || [],
      live_follow_up: relocation?.live_follow_up || null,
      navigation_edit: relocation?.navigation_edit || null,
    };
  });
  return { schema_version: 1, repository, note: 'Location inventory only. Original verdicts, authority and carried conditions are unchanged.', entries };
}

function writeArchiveIndex(repository, root, complete) {
  const index = buildArchiveIndex(repository, root, complete);
  fs.mkdirSync(path.join(root, 'archive'), { recursive: true });
  fs.writeFileSync(path.join(root, 'archive/index.json'), JSON.stringify(index, null, 2) + '\n');
  const lines = ['# Archive inventory', '', index.note, '',
    'Generated by the platform `npm run agent:index` command. Use the original view to follow links relative to preserved historical records.', '',
    '| Archived file | Original view | Topic | Current consumers / follow-up |', '|---|---|---|---|'];
  for (const e of index.entries) {
    const relative = e.archived_path.slice('archive/'.length).split('/').map(encodeURIComponent).join('/');
    const follow = [...e.current_consumers, e.live_follow_up].filter(Boolean).join(', ') || 'Historical lookup; no new authority';
    lines.push(`| [${e.archived_path.replace(/\|/g, '\\|')}](${relative}) | [${e.original_path.replace(/\|/g, '\\|')}](${e.original_url}) | ${e.topic} | ${follow} |`);
  }
  fs.writeFileSync(path.join(root, 'archive/index.md'), lines.join('\n') + '\n');
}
module.exports = { buildArchiveIndex, writeArchiveIndex };
