#!/usr/bin/env node
/**
 * generate-all.js
 *
 * Builds JSON-first reference health reports plus Markdown projections.
 * Reports are diagnostic generated artifacts; they do not replace source data.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const REPO_ROOT = path.resolve(__dirname, '..', '..');
const JSON_DIR = path.join(REPO_ROOT, 'reports/json');
const MD_DIR = path.join(REPO_ROOT, 'reports/markdown');
const UNITS = 'references/machine/micro-teaching-units.json';
const TERMS = 'references/machine/begrippen.json';
const EXAMS = 'references/external/exam-questions.json';
const TARGETS = 'references/authored/course-target-exercises.json';
const EMPTY_NEEDS = 'references/data/audits/empty-needs-audit.json';

function readJson(relPath, fallback) {
  const file = path.join(REPO_ROOT, relPath);
  if (!fs.existsSync(file)) return fallback;
  return JSON.parse(fs.readFileSync(file, 'utf8'));
}

function rel(file) {
  return path.relative(REPO_ROOT, file).replace(/\\/g, '/');
}

function now() {
  return new Date().toISOString();
}

function sha(text) {
  return crypto.createHash('sha256').update(text).digest('hex');
}

function issue(reportId, index, severity, affectedEntity, category, evidencePath, nextAction, proofRequiredToClose) {
  return {
    issue_id: `${reportId}-${String(index).padStart(4, '0')}`,
    severity,
    affected_entity: affectedEntity,
    category,
    evidence_path: evidencePath,
    next_action: nextAction,
    proof_required_to_close: proofRequiredToClose,
  };
}

function makeReport(reportId, sourceFiles, status, issues, summary = {}) {
  return {
    report_id: reportId,
    generated_by: 'build-scripts/reports/generate-all.js',
    generated_on: now(),
    source_files: sourceFiles,
    schema_version: 1,
    status,
    summary,
    issues,
  };
}

function writeReport(report) {
  fs.mkdirSync(JSON_DIR, { recursive: true });
  fs.mkdirSync(MD_DIR, { recursive: true });
  fs.writeFileSync(path.join(JSON_DIR, `${report.report_id}.json`), JSON.stringify(report, null, 2) + '\n');

  const lines = [];
  lines.push(`# ${report.report_id}`);
  lines.push('');
  lines.push(`Generated: ${report.generated_on}`);
  lines.push(`Status: ${report.status}`);
  lines.push(`Generated by: \`${report.generated_by}\``);
  lines.push('');
  lines.push('## Summary');
  lines.push('');
  for (const [key, value] of Object.entries(report.summary || {})) {
    lines.push(`- ${key}: ${typeof value === 'object' ? JSON.stringify(value) : value}`);
  }
  if (Object.keys(report.summary || {}).length === 0) lines.push('No summary fields.');
  lines.push('');
  lines.push('## Issues');
  lines.push('');
  if (report.issues.length === 0) {
    lines.push('None.');
  } else {
    for (const item of report.issues) {
      lines.push(`- **${item.severity}** ${item.affected_entity} (${item.category})`);
      lines.push(`  - evidence: \`${item.evidence_path}\``);
      lines.push(`  - next: ${item.next_action}`);
      lines.push(`  - close: ${item.proof_required_to_close}`);
    }
  }
  fs.writeFileSync(path.join(MD_DIR, `${report.report_id}.md`), lines.join('\n').replace(/\n+$/g, '') + '\n');
}

function loadUnits() {
  const units = readJson(UNITS, []);
  return {
    all: units,
    live: units.filter((unit) => !unit.deprecated),
    deprecated: units.filter((unit) => unit.deprecated),
    byId: new Map(units.map((unit) => [unit.id, unit])),
  };
}

function loadTerms() {
  const data = readJson(TERMS, { terms: {} });
  return data.terms || {};
}

function collectCitations() {
  const files = [];
  const roots = ['references', 'reports', 'knowledge', 'docs'];
  for (const root of roots) {
    const fullRoot = path.join(REPO_ROOT, root);
    if (!fs.existsSync(fullRoot)) continue;
    const stack = [fullRoot];
    while (stack.length) {
      const current = stack.pop();
      for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
        const full = path.join(current, entry.name);
        if (entry.isDirectory()) {
          if (!['node_modules', '.git'].includes(entry.name)) stack.push(full);
        } else if (/\.(md|json|js|jsonl)$/i.test(entry.name)) {
          files.push(full);
        }
      }
    }
  }
  return files;
}

function buildDagIntegrity(ctx) {
  const issues = [];
  let i = 1;
  for (const unit of ctx.units.all) {
    for (const need of unit.needs || []) {
      if (!ctx.units.byId.has(need)) {
        issues.push(issue('dag-integrity', i++, 'critical', unit.id, 'missing_need_reference', UNITS, `Create or correct prerequisite ${need}.`, 'All needs references resolve.'));
      }
    }
  }

  const visiting = new Set();
  const visited = new Set();
  function visit(id, pathSoFar) {
    if (visiting.has(id)) {
      issues.push(issue('dag-integrity', i++, 'critical', id, 'cycle', UNITS, `Break dependency cycle ${[...pathSoFar, id].join(' -> ')}.`, 'Dependency graph is acyclic.'));
      return;
    }
    if (visited.has(id)) return;
    visiting.add(id);
    const unit = ctx.units.byId.get(id);
    for (const need of (unit && unit.needs) || []) if (ctx.units.byId.has(need)) visit(need, [...pathSoFar, id]);
    visiting.delete(id);
    visited.add(id);
  }
  for (const unit of ctx.units.all) visit(unit.id, []);

  return makeReport('dag-integrity', [UNITS], issues.length ? 'fail' : 'pass', issues, {
    units: ctx.units.all.length,
    live_units: ctx.units.live.length,
    deprecated_units: ctx.units.deprecated.length,
  });
}

function buildTerminologyDrift(ctx) {
  const canonical = new Set(Object.keys(ctx.terms));
  const issues = [];
  let i = 1;
  let termCitations = 0;
  for (const unit of ctx.units.all) {
    for (const term of unit.terms || []) {
      termCitations++;
      if (!canonical.has(term)) {
        issues.push(issue('terminology-drift', i++, 'medium', unit.id, 'noncanonical_term', UNITS, `Resolve term ${term} through term registry or unit update.`, 'Unit term resolves to begrippen.json.'));
      }
    }
  }
  return makeReport('terminology-drift', [UNITS, TERMS], issues.length ? 'fail' : 'pass', issues, {
    term_registry_entries: canonical.size,
    unit_term_citations: termCitations,
  });
}

function buildUnresolvedRefs(ctx) {
  const deprecated = new Set(ctx.units.deprecated.map((unit) => unit.id));
  const issues = [];
  let i = 1;
  for (const file of collectCitations()) {
    const text = fs.readFileSync(file, 'utf8');
    for (const id of deprecated) {
      if (new RegExp(`\\b${id}\\b`).test(text)) {
        issues.push(issue('unresolved-refs', i++, 'low', id, 'deprecated_reference', rel(file), 'Remove or migrate deprecated unit citation.', 'No deprecated unit ID is cited from active docs/reports.'));
      }
    }
  }
  return makeReport('unresolved-refs', [UNITS, 'references/', 'reports/', 'knowledge/', 'docs/'], issues.length ? 'warn' : 'pass', issues, {
    deprecated_units: deprecated.size,
    deprecated_citations: issues.length,
  });
}

function buildNeedsCoverage(ctx) {
  const issues = [];
  let i = 1;
  for (const unit of ctx.units.live) {
    if (!Array.isArray(unit.needs) || unit.needs.length === 0) {
      const status = unit.zero_needs_status || 'unclassified';
      const severity = ['underbouw_assumed', 'true_zero'].includes(status) ? 'info' : status === 'false_zero' ? 'high' : 'medium';
      issues.push(issue('needs-coverage', i++, severity, unit.id, `empty_needs:${status}`, UNITS, 'Review whether this is true zero, underbouw assumed, or false zero.', 'Unit has explicit zero-needs status or at least one validated prerequisite.'));
    }
  }
  return makeReport('needs-coverage', [UNITS], issues.length ? 'warn' : 'pass', issues, {
    live_units: ctx.units.live.length,
    empty_needs: issues.length,
  });
}

function buildTermsCoverage(ctx) {
  const issues = [];
  let i = 1;
  for (const unit of ctx.units.live) {
    if (!Array.isArray(unit.terms) || unit.terms.length === 0) {
      issues.push(issue('terms-coverage', i++, 'medium', unit.id, 'missing_term_links', UNITS, 'Add canonical term slugs when this unit uses glossary concepts.', 'Unit terms are either populated or explicitly marked not applicable.'));
    }
  }
  return makeReport('terms-coverage', [UNITS, TERMS], issues.length ? 'warn' : 'pass', issues, {
    live_units: ctx.units.live.length,
    units_without_terms: issues.length,
  });
}

function buildProcedureCoverage(ctx) {
  const issues = [];
  let i = 1;
  for (const unit of ctx.units.live) {
    if (unit.mastery_target === 'apply' && (!Array.isArray(unit.procedure) || unit.procedure.length === 0)) {
      issues.push(issue('procedure-coverage', i++, 'medium', unit.id, 'missing_procedure', UNITS, 'Add a procedure or lower mastery target.', 'Apply-level unit has a procedure.'));
    }
  }
  return makeReport('procedure-coverage', [UNITS], issues.length ? 'warn' : 'pass', issues, {
    live_units: ctx.units.live.length,
    apply_units_without_procedure: issues.length,
  });
}

function buildAspectsCoverage(ctx) {
  const issues = [];
  let i = 1;
  for (const unit of ctx.units.live) {
    if (!Array.isArray(unit.aspects) || unit.aspects.length === 0) {
      issues.push(issue('aspects-coverage', i++, 'low', unit.id, 'missing_aspects', UNITS, 'Assign aspect tags when production planning uses this unit.', 'Unit has aspect tags or an explicit no-aspect rationale.'));
    }
  }
  return makeReport('aspects-coverage', [UNITS], issues.length ? 'warn' : 'pass', issues, {
    live_units: ctx.units.live.length,
    units_without_aspects: issues.length,
  });
}

function usedUnitIds(ctx) {
  const used = new Set();
  for (const question of ctx.exams.questions || ctx.exams || []) {
    for (const id of question.required_skills || question.skill_ids || []) used.add(id);
  }
  const targetText = JSON.stringify(ctx.targets);
  for (const unit of ctx.units.all) if (new RegExp(`\\b${unit.id}\\b`).test(targetText)) used.add(unit.id);
  return used;
}

function buildDeadUnits(ctx) {
  const used = usedUnitIds(ctx);
  const issues = [];
  let i = 1;
  for (const unit of ctx.units.live) {
    if (!used.has(unit.id)) {
      issues.push(issue('dead-units', i++, 'low', unit.id, 'uncited_live_unit', UNITS, 'Check whether this unit is future-needed, should be cited, or should be deprecated.', 'Unit is cited by exam/target evidence or explicitly marked intentionally uncited.'));
    }
  }
  return makeReport('dead-units', [UNITS, EXAMS, TARGETS], issues.length ? 'warn' : 'pass', issues, {
    live_units: ctx.units.live.length,
    cited_live_units: ctx.units.live.length - issues.length,
    uncited_live_units: issues.length,
  });
}

function buildBegrippenCoverage(ctx) {
  const issues = [];
  let i = 1;
  for (const [id, term] of Object.entries(ctx.terms)) {
    if (!Array.isArray(term.teaching_units) || term.teaching_units.length === 0) {
      issues.push(issue('begrippen-coverage', i++, 'low', id, 'term_without_teaching_units', TERMS, 'Link term to teaching units when used in production.', 'Term has teaching_units or explicit orphan rationale.'));
    }
  }
  return makeReport('begrippen-coverage', [TERMS, UNITS], issues.length ? 'warn' : 'pass', issues, {
    terms: Object.keys(ctx.terms).length,
    terms_without_teaching_units: issues.length,
  });
}

function buildEmptyNeedsAuditSummary(ctx) {
  const audit = ctx.emptyNeeds;
  const issues = [];
  let i = 1;
  for (const entry of audit.entries || []) {
    if (['false_zero', 'ambiguous'].includes(entry.recommended_status)) {
      issues.push(issue('empty-needs-audit-summary', i++, entry.severity || 'medium', entry.unit_id, `empty_needs_review:${entry.recommended_status}`, EMPTY_NEEDS, entry.human_question || 'Review empty-needs classification.', 'Human review or mutation workflow closes this entry.'));
    }
  }
  return makeReport('empty-needs-audit-summary', [EMPTY_NEEDS], issues.length ? 'warn' : 'info', issues, {
    live_unit_count: audit.live_unit_count || null,
    empty_needs_count: audit.empty_needs_count || null,
    by_status: audit.summary && audit.summary.by_status ? audit.summary.by_status : {},
  });
}

function main() {
  const ctx = {
    units: loadUnits(),
    terms: loadTerms(),
    exams: readJson(EXAMS, []),
    targets: readJson(TARGETS, {}),
    emptyNeeds: readJson(EMPTY_NEEDS, { entries: [], summary: {} }),
  };

  const reports = [
    buildDagIntegrity(ctx),
    buildTerminologyDrift(ctx),
    buildUnresolvedRefs(ctx),
    buildNeedsCoverage(ctx),
    buildTermsCoverage(ctx),
    buildProcedureCoverage(ctx),
    buildAspectsCoverage(ctx),
    buildDeadUnits(ctx),
    buildBegrippenCoverage(ctx),
    buildEmptyNeedsAuditSummary(ctx),
  ];

  for (const report of reports) writeReport(report);

  const manifest = {
    generated_by: 'build-scripts/reports/generate-all.js',
    generated_on: now(),
    report_count: reports.length,
    reports: reports.map((report) => ({
      report_id: report.report_id,
      status: report.status,
      issue_count: report.issues.length,
      json_path: `reports/json/${report.report_id}.json`,
      markdown_path: `reports/markdown/${report.report_id}.md`,
      content_hash: sha(JSON.stringify(report)),
    })),
  };
  fs.writeFileSync(path.join(JSON_DIR, 'report-manifest.json'), JSON.stringify(manifest, null, 2) + '\n');
  console.log(`OK generated ${reports.length} JSON-first report(s). Manifest: reports/json/report-manifest.json`);
}

if (require.main === module) main();
