// Classroom presentation, Book 1 second edition 2026. Runtime paths come from the installed skill.
import fs from 'node:fs/promises';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {Presentation,PresentationFile,finalizePresentation,applyPresentationChartFont,PYTHON,SKILL,TOOLS,workspace} from '../../presentations/runtime.mjs';
const {root:ROOT,build:BUILD,final:FINAL}=await workspace('133');
const M=JSON.parse(await fs.readFile(new URL('./presentation-133.tweede-editie-2026.manifest.json',import.meta.url),'utf8'));
const p=Presentation.create({slideSize:{width:1600,height:900}});
const C={ink:'#183247',blue:'#1A5276',green:'#20665B',orange:'#A94D16',purple:'#704798',line:'#C6D2DB',pale:'#EFF4F7',muted:'#445B6B'};
const FONT='Arial',TITLE='Verschuivingen en nieuw evenwicht',slides=[],tables=[],charts=[],graphs=[];
const source='https://github.com/meijer1973/4veco-lessen/blob/'+M.lessonCommit+'/'+encodeURI(M.sourceEdition)+'/';
function text(s,str,x,y,w,h,size=36,{bold=false,color=C.ink,align='left',name}={}){const q=s.shapes.add({geometry:'textbox',name:name||str.slice(0,60),position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});q.text=str;q.text.style={typeface:FONT,fontSize:size,bold,color,alignment:align,verticalAlignment:'top',autoFit:'none',wrap:'square',insets:{left:0,right:0,top:0,bottom:0}};return q;}
function rule(s,x,y,w){s.shapes.add({geometry:'line',position:{left:x,top:y,width:w,height:0},line:{fill:C.line,width:2}});}
function slide(t,role='instruction'){const s=p.slides.add();s.background.fill='#FFFFFF';text(s,t,60,42,1480,78,t.startsWith('Deze les')?45:50,{bold:true});rule(s,60,146,1480);text(s,'§1.3.3 '+TITLE+(role.startsWith('target')?' · Opgave 31 · p. 116':''),60,848,1390,30,21,{color:C.muted});text(s,String(p.slides.items.length),1470,845,70,32,22,{align:'right',color:C.muted});slides.push({number:p.slides.items.length,title:t,role});return s;}
function notes(s,page,explanation,question,pitfall,transition,authored=false){s.speakerNotes.textFrame.setText(`Vraag: ${question}\n\nUitleg: ${explanation}\n\nMisvatting: ${pitfall}\n\nOvergang: ${transition}\n\nBron: Boek 1, tweede editie 2026, compleet leerlingenboek, gedrukte pagina ${page}. ${source}boek/Boek_1_Compleet_Tweede_editie.pdf\nMethode en opgaven: ${source}bronnen/H3/1.3.3%20Verschuivingen%20en%20nieuw%20evenwicht%20%E2%80%93%20paragraaf.md\nAntwoordmodel: ${source}bronnen/H3/Antwoorden.md#answer31\n${authored?'Uitlegvoorbeeld — niet uit het boek. Context en gegevens over sleutelhangers zijn afzonderlijk voor deze les gemaakt. De boekpagina onderbouwt de methode, niet deze gegevens.':''}`);}
function table(s,values,x,y,w,h,widths,size=33){const t=s.tables.add({rows:values.length,columns:values[0].length,left:x,top:y,width:w,height:h,columnWidths:widths,values});t.borders.assign({fill:C.line,width:1,style:'solid'});for(let r=0;r<values.length;r++){t.rows[r].height=h/values.length;for(let c=0;c<values[0].length;c++){const a=t.getCell(r,c);a.fill=r===0?C.ink:(r%2?'#FFFFFF':C.pale);a.text.style={typeface:FONT,fontSize:size,color:r===0?'#FFFFFF':C.ink,bold:r===0,verticalAlignment:'middle',insets:{left:18,right:14,top:10,bottom:10}};}}tables.push(p.slides.items.length);return t;}
function ex(t){const s=slide(t,'teaching-example');text(s,'Uitlegvoorbeeld — niet uit het boek',60,178,1480,44,28,{color:C.muted});return s;}
function target(t,questions=false){return slide(t,questions?'target-question':'target-answer');}
const overviewData={route:['Jas in de kluis of aan de kapstok. Pak agenda, schrift, pen en rekenmachine.','Maak de startopdracht.','Uitleg bij de lesdoelen.','Begin bij de basisopgaven en stel vragen. Lukt dat goed, ga dan naar de zelfstandige oefening. Maak daarna de doelopgave en kijk vervolgens je antwoorden na.','Klaar? Werk aan een ander vak. Geen devices.','Bespreken van de doelopgave: opgave 31.','Zet je huiswerk in je agenda.'],goals:'Oorzaak en prijsreactie scheiden.\nOud en nieuw evenwicht berekenen.\nVerschuiving en beweging tekenen.',start:'Pagina 112 · Opgaven 23 en 24\n24: verkennen met theorie\np. 108–109',homework:'§1.3.3\nBasis: 25, 26 en 27\nZelfstandig: 28, 29 en 30\nDoelopgave: 31\nMaken en nakijken'};
function overview(phase,active){const s=slide('Deze les: §1.3.3 '+TITLE,'overview');text(s,'Nu: '+phase,60,111,1460,43,30,{bold:true,color:C.blue,name:'phase'});text(s,'Lesroute',60,185,835,45,35,{bold:true});const ys=[244,336,390,446,636,716,774],hs=[80,45,45,177,73,50,52];overviewData.route.forEach((r,i)=>{const col=active===i+1?C.blue:C.ink;text(s,`${i+1}.`,60,ys[i],48,hs[i],30,{bold:true,color:col,name:'route-number-'+i});text(s,r,116,ys[i],779,hs[i],30,{bold:active===i+1,color:col,name:'route-'+i});});text(s,'Lesdoelen',972,185,565,45,35,{bold:true});text(s,overviewData.goals,972,244,565,122,30,{name:'overview-goals'});rule(s,972,374,568);text(s,'Startopdracht',972,397,565,45,35,{bold:true,color:active===2?C.blue:C.ink});text(s,overviewData.start,972,449,565,115,30,{bold:active===2,name:'overview-start'});rule(s,972,577,568);text(s,'Huiswerk',972,597,565,45,35,{bold:true,color:active===7?C.blue:C.ink});text(s,overviewData.homework,972,651,565,178,30,{bold:active===7,name:'overview-homework'});notes(s,'112–116',`Laat deze dia staan tijdens ${phase.toLowerCase()}. Start 23–24 en basis 25 staan op p.112, basis 26 op p.113, basis 27 en zelfstandig 28 op p.114, zelfstandig 29–30 op p.115, doel 31 op p.116. Huiswerk: 25,26,27,28,29,30,31 maken en nakijken. Bonus 32 en herhaling 33 zijn extra. De normale route mag over meerdere lessen lopen.\n\nStart 23 haalt de procentuele verandering op, expliciet geleerd op p.14. Bij haperen: nieuw min oud, delen door oud, maal 100%. Start 24 combineert eerdere kennis (aantal kopers p.59–60, aanbodfactor versus eigen prijs p.88, prijsreactie langs bestaande lijnen p.99) in een nieuw evenwichtsscenario. Laat leerlingen p.108–109 gebruiken: eerst oorzaak en vaste-prijsvergelijking, daarna de reactie van verkopers. Hun poging is een ondersteunde verkenning. Onthul de uitwerking niet vooraf. Bij terugkeer vóór het basiswerk laat je 24 opnieuw beantwoorden met oorzaak én reactie en bespreek je twijfel. Vraag leerlingen ook 23 te controleren met de oude hoeveelheid als basis.`,active===2?'Welke eerdere methode herken je, en waar heb je theorie nodig?':'Welke stap in de oefenroute werk je nu uit?','Een vraag in het boek bewijst nog geen beheerste voorkennis. Controleer de redenering in het schrift.',active===7?'Laat het huiswerk in de agenda noteren.':'Ga verder wanneer de klas aan de volgende fase toe is.');}
const E={id:'example',unit:'sleutelhangers per week',single:'sleutelhanger',v0:72,v1:90,b:3,a0:-12,a1:-30,d:3,q0:30,p0:14,q1:39,p1:17,qs:21,ps:17,xmax:90,ymax:30,xstep:15,ystep:5};
const T={id:'target',unit:'kabels per week',single:'kabel',v0:100,v1:120,b:5,a0:-20,d:5,q0:40,p0:12,q1:50,p1:14,xmax:120,ymax:24,xstep:20,ystep:4};
// Required economics diagrams are editable XY charts. Arrow heads are native XY segments.
function graph(s,m,stage){const series=[];const add=(name,x,y,color,style='solid',width=3)=>series.push({name,xValues:x,values:y,line:{fill:color,width,style},marker:{symbol:'none'}});const label=(name,x,y,color=C.ink)=>series.push({name,xValues:[x],values:[y],line:{fill:'none',width:0},marker:{symbol:'none'},dataLabelOverrides:[{idx:0,text:name,position:'t',showValue:false,textStyle:{typeface:FONT,fontSize:28,fill:color,bold:true}}]});const point=(name,q,pr)=>series.push({name,xValues:[q],values:[pr],line:{fill:'none',width:0},marker:{symbol:'circle',size:9,fill:C.ink,line:{fill:C.ink,width:1}}});const supplyShift=stage==='supply',demandShift=['shift','new','arrows'].includes(stage);
add('V₀',[0,m.v0],[m.v0/m.b,0],C.blue);add('A₀',[0,m.d*m.ymax+m.a0],[-m.a0/m.d,m.ymax],C.green);label('V₀',m.v0*.88,(m.v0-m.v0*.88)/m.b+1.1,C.blue);label(supplyShift?'A₀':'A',m.d*(m.ymax*.86)+m.a0,m.ymax*.86-1.0,C.green);
if(demandShift){add('V₁',[0,m.v1],[m.v1/m.b,0],C.purple,'dashed',4);label('V₁',m.v1*.90,(m.v1-m.v1*.90)/m.b+.5,C.purple);}
if(supplyShift){add('A₁',[0,m.d*m.ymax+m.a1],[-m.a1/m.d,m.ymax],C.orange,'dashed',4);label('A₁',m.d*(m.ymax*.91)+m.a1,m.ymax*.91-1.0,C.orange);}
function guides(q,pr){add('P hulplijn '+q,[0,q],[pr,pr],C.muted,'dashed',1.5);add('Q hulplijn '+q,[q,q],[0,pr],C.muted,'dashed',1.5);}
if(stage!=='base'){guides(m.q0,m.p0);point('E₀ punt',m.q0,m.p0);label('E₀',m.q0-m.xmax*.045,m.p0+m.ymax*.055);}
if(['new','arrows','supply'].includes(stage)){const q=supplyShift?m.qs:m.q1,pr=supplyShift?m.ps:m.p1;guides(q,pr);point('E₁ punt',q,pr);label('E₁',q-m.xmax*.035,pr+m.ymax*.09);}
function arrow(name,x0,y0,x1,y1,color){add(name,[x0,x1],[y0,y1],color,'solid',4);const dx=(x1-x0)/m.xmax,dy=(y1-y0)/m.ymax,len=Math.hypot(dx,dy),ux=dx/len,uy=dy/len;const head=.022,wing=.012;add(name+' punt',[(x1/m.xmax-head*ux+wing*uy)*m.xmax,x1,(x1/m.xmax-head*ux-wing*uy)*m.xmax],[(y1/m.ymax-head*uy-wing*ux)*m.ymax,y1,(y1/m.ymax-head*uy+wing*ux)*m.ymax],color,'solid',4);}
if(['shift','arrows'].includes(stage))arrow('Verschuiving bij oude prijs',m.q0,m.p0,m.v1-m.b*m.p0,m.p0,C.purple);
if(stage==='arrows')arrow('Beweging langs A',m.q0,m.p0,m.q1,m.p1,C.orange);
if(supplyShift){arrow('Aanbodverschuiving bij oude prijs',m.q0,m.p0,m.d*m.p0+m.a1,m.p0,C.orange);arrow('Beweging langs V',m.q0,m.p0,m.qs,m.ps,C.purple);}
for(const a of series){a.xValues=a.xValues.map(v=>+v.toFixed(6));a.values=a.values.map(v=>+v.toFixed(6));}
const ch=s.charts.add('scatter',{position:{left:60,top:242,width:995,height:583},series,scatterOptions:{style:'line'},hasLegend:false,xAxis:{min:0,max:m.xmax,majorUnit:m.xstep,numberFormatCode:'0',title:{text:'Q ('+m.unit+')',textStyle:{typeface:FONT,fontSize:27,fill:C.ink}},textStyle:{typeface:FONT,fontSize:26,fill:C.ink},line:{fill:C.ink,width:1.5}},yAxis:{min:0,max:m.ymax,majorUnit:m.ystep,numberFormatCode:'0',title:{text:'P (€ per '+m.single+')',textStyle:{typeface:FONT,fontSize:27,fill:C.ink}},textStyle:{typeface:FONT,fontSize:26,fill:C.ink},majorGridlines:{fill:C.line,width:1},line:{fill:C.ink,width:1.5}},chartFill:'#FFFFFF',plotAreaFill:'#FFFFFF'});applyPresentationChartFont(ch,{fontFamily:FONT});charts.push(p.slides.items.length);graphs.push({slide:p.slides.items.length,model:m,stage,series});}
function lines(s,rows,{y=265,gap=112,size=42}={}){rows.forEach((r,i)=>text(s,r,60,y+i*gap,1480,96,size,{bold:i===rows.length-1,color:i===rows.length-1?C.blue:C.ink}));}

overview('Startopdracht',2);
{
const s=slide('Oorzaak, plannen en nieuw evenwicht');
const rows=[['Oorzaak','Welke factor verandert vraag of aanbod?'],['Oude prijs','Welke plannen botsen bij diezelfde prijs?'],['Nieuw evenwicht','Stel de nieuwe functies gelijk en controleer Q.'],['Vergelijking','Bereken de verandering en teken beide pijlen.']];rows.forEach((a,i)=>{let y=215+i*142;text(s,a[0],60,y,430,70,40,{bold:true,color:C.blue});text(s,a[1],540,y,985,100,38);if(i<3)rule(s,60,y+105,1480);});notes(s,'108–111','Deze route combineert vaardigheden uit vorige lessen: gelijkstellen en beide functies controleren op p.98, twee punten per lijn op p.97 en101, procentuele verandering op p.14. Vraag naar de grootheden: Q horizontaal, P verticaal. Controleer steeds of P binnen de opgegeven domeinen ligt.','Waarom vergelijk je de oude en nieuwe plannen eerst bij dezelfde prijs?','Een nieuwe evenwichtsprijs is een gevolg van een factorverandering, geen bewijs dat beide lijnen verschoven.','Pas de route toe op een afzonderlijk uitlegvoorbeeld.');
}
{
const s=ex('De markt voor sleutelhangers');text(s,'Q: sleutelhangers per week. P: euro per sleutelhanger.',60,250,1480,70,35,{bold:true});table(s,[['Beginsituatie','Functie','Geldige prijzen'],['Vraag','Qᵥ,₀ = 72 − 3P','0 ≤ P ≤ 24'],['Aanbod','Qₐ = 3P − 12','4 ≤ P ≤ 30']],60,355,1480,285,[450,610,420],35);text(s,'Daarna komen meer kopers. De aanbodfactoren blijven gelijk.',60,703,1480,108,40,{bold:true,color:C.blue});notes(s,'108','Nieuwe, zelfgeschreven markt. Eerst reconstrueren we de beginmarkt. Pas daarna veranderen we het aantal kopers. Q is de gezamenlijke markt en geen individuele vraag.','Welke twee plannen moeten in evenwicht gelijk zijn?','De nieuwe kopers horen nog niet bij de berekening van E₀.','Bereken de oorspronkelijke evenwichtsprijs.',true);
}
{
const s=ex('Het oorspronkelijke evenwicht');lines(s,['72 − 3P = 3P − 12','84 = 6P','P₀ = € 14 per sleutelhanger'],{y:264,gap:103});rule(s,60,579,1480);text(s,'Qᵥ,₀ = 72 − 3 × 14 = 30\nControle: Qₐ = 3 × 14 − 12 = 30 per week',60,624,1480,138,42);text(s,'E₀ = (30; 14)',60,787,1480,51,35,{bold:true,color:C.blue});notes(s,'98, 108–109','Voeg 3P aan beide kanten toe, tel aan beide kanten 12 erbij en deel door 6. Vul de gevonden prijs in beide functies in. Beide domeinen bevatten 14. Herhaal dat E altijd (Q; P) noteert.','Welke functie gebruik je voor de onafhankelijke controle?','E₀ = (14; 30) verwisselt de assen.','Plaats dit evenwicht op de twee oorspronkelijke lijnen.',true);
}
{
const s=ex('De beginmarkt tekenen');graph(s,E,'old');text(s,'Twee punten per lijn',1110,276,420,65,35,{bold:true});text(s,'V₀: (0; 24)\nen (72; 0)\n\nA: (0; 4)\nen (78; 30)',1110,377,420,275,35);text(s,'E₀ = (30; 14)',1110,741,420,65,38,{bold:true,color:C.blue});notes(s,'97–98, 101, 108','Voor V: Q = 0 geeft P = 24 en P = 0 geeft Q = 72. Voor A: Q = 0 geeft P = 4 en P = 30 geeft Q = 78. Verbind elk paar met een rechte lijn. Hun snijpunt past bij de berekening. De hulplijnen verbinden E₀ met beide assen.','Hoe vind je een tweede punt op A zonder een negatieve hoeveelheid te tekenen?','Gebruik alleen de opgegeven domeinen. Onder P = 4 kent dit aanbodmodel geen negatieve hoeveelheid.','Vergelijk de vraagplannen nadat er meer kopers zijn.',true);
}
{
const s=ex('Meer kopers bij de oude prijs');text(s,'Nieuwe vraag: Qᵥ,₁ = 90 − 3P   (0 ≤ P ≤ 30)',60,258,1480,80,42,{bold:true,color:C.purple});table(s,[['Bij P₀ = € 14','Berekening','Sleutelhangers per week'],['Nieuwe vraag','90 − 3 × 14','48'],['Ongewijzigd aanbod','3 × 14 − 12','30']],60,378,1480,281,[540,440,500],34);text(s,'Vraagoverschot: 48 − 30 = 18 per week',60,708,1480,62,43,{bold:true});text(s,'Kopers concurreren om het aanbod: opwaartse prijsdruk.',60,789,1480,52,34,{color:C.blue});notes(s,'108–109','De specifieke factor is het aantal kopers. Bij elke prijs in het gemeenschappelijke domein ligt de vraag 18 hoger. Bij de oude prijs botsen 48 koopplannen met 30 verkoopplannen. De prijs mag zich in dit model aanpassen.','Is 48 al de nieuwe evenwichtshoeveelheid?','48 is de nieuwe gevraagde hoeveelheid bij de oude prijs, niet de uiteindelijke verkoop in evenwicht.','Teken eerst alleen de verschuiving.',true);
}
{
const s=ex('De verschuiving bij dezelfde prijs');graph(s,E,'shift');text(s,'V₁ door\n(0; 30) en (90; 0)',1110,265,420,117,36,{bold:true,color:C.purple});text(s,'Bij € 14:\n30 wordt 48\n\nHorizontale pijl:\n18 extra gevraagd',1110,426,420,237,35);text(s,'A blijft dezelfde lijn.',1110,733,420,97,36,{bold:true,color:C.green});notes(s,'108–109','Bereken eerst beide assnijpunten van de nieuwe vraaglijn: bij Q = 0 is P = 30, bij P = 0 is Q = 90. De horizontale pijl loopt van (30; 14) op V₀ naar (48; 14) op V₁. Elke pijl houdt dezelfde prijs vast. Het nieuwe snijpunt rekenen we hierna uit.','Wat verandert en wat houd je bij de horizontale pijl gelijk?','De verschuiving heeft lengte 18 sleutelhangers, geen 18 euro.','Los nu de nieuwe gelijkheid op.',true);
}
{
const s=ex('Het nieuwe evenwicht berekenen');lines(s,['90 − 3P = 3P − 12','102 = 6P','P₁ = € 17 per sleutelhanger'],{y:258,gap:95});text(s,'Qᵥ,₁ = 90 − 3 × 17 = 39\nControle: Qₐ = 3 × 17 − 12 = 39 per week',60,578,1480,136,41);text(s,'Verandering Q: (39 − 30) / 30 × 100% = +30%',60,761,1480,75,39,{bold:true,color:C.orange});notes(s,'14, 109, 111','Vervang uitsluitend de vraagfunctie. Voeg 3P toe aan beide kanten, tel 12 erbij en deel door 6. Prijs 17 past in beide domeinen. Q stijgt van 30 naar 39: 9 / 30 × 100% = 30%. De 18 extra vraag bij de oude prijs wordt geen 18 extra evenwichtshoeveelheid: de hogere prijs remt de gevraagde hoeveelheid langs V₁.','Welke hoeveelheid hoort als oude basis onder de breuk?','Deel niet door 39 en gebruik niet 48 als de nieuwe evenwichtshoeveelheid.','Laat de twee verschillende veranderingen in één grafiek zien.',true);
}
{
const s=ex('Verschuiving en beweging zijn verschillende stappen');graph(s,E,'arrows');text(s,'E₀ = (30; 14)\nE₁ = (39; 17)',1110,267,420,131,39,{bold:true});text(s,'Paars: meer kopers\nbij dezelfde prijs.',1110,451,420,125,35,{color:C.purple});text(s,'Oranje: hogere prijs,\nmeer aangeboden\nlangs dezelfde A.',1110,638,420,178,35,{bold:true,color:C.orange});notes(s,'109','Van E₀ naar E₁ bewegen verkopers langs A. Alleen het aantal kopers veranderde. De prijsreactie brengt zowel een beweging langs A als langs de nieuwe V₁ mee; de vraaglijn zelf verschuift niet nogmaals. P en Q kunnen samen stijgen doordat E₀ en E₁ op verschillende vraaglijnen liggen.','Welke pijl toont de oorzaak en welke pijl de reactie van de verkopers?','Een grotere aangeboden hoeveelheid bewijst geen verschuiving van de aanbodlijn.','Start een afzonderlijk scenario met dezelfde beginmarkt.',true);
}
{
const s=ex('Afzonderlijk scenario: duurder metaal');text(s,'Opnieuw de beginmarkt. De extra kopers zijn er nu niet.',60,255,1480,70,37,{bold:true});text(s,'Qᵥ = 72 − 3P blijft. Nieuw: Qₐ,₁ = 3P − 30 (10 ≤ P ≤ 30).',60,354,1480,97,37,{bold:true,color:C.orange});table(s,[['Bij de oude prijs € 14','Vraag','Nieuw aanbod'],['Berekening','72 − 3 × 14 = 30','3 × 14 − 30 = 12']],60,503,1480,194,[530,475,475],34);text(s,'Vraagoverschot: 30 − 12 = 18 per week. De prijs stijgt.',60,749,1480,89,40,{bold:true});notes(s,'110–111','Reset naar de oorspronkelijke functies 72 − 3P en 3P − 12. Alleen metaal, een productiemiddel, wordt duurder. Het aantal kopers is gelijk aan het begin. Bij P = 14 zakt aanbod van 30 naar 12, dus A verschuift links.','Waarom gebruik je nu niet 90 − 3P?','Scenario’s zijn afzonderlijk. De vraagverschuiving uit het vorige scenario wordt niet meegenomen.','Bereken het nieuwe evenwicht en volg de kopers langs V.',true);
}
{
const s=ex('Een aanbodverschuiving en de reactie van kopers');graph(s,E,'supply');text(s,'72 − 3P = 3P − 30\n102 = 6P\nP₁ = € 17',1110,253,420,207,36,{bold:true});text(s,'Qᵥ = 72 − 51 = 21\nQₐ,₁ = 51 − 30 = 21',1110,496,420,134,33);text(s,'A naar links.\nE₀ naar E₁ langs V₀.\nQ daalt: 30 naar 21.',1110,683,420,141,33,{bold:true,color:C.orange});notes(s,'110–111','De nieuwe aanbodlijn gaat door (0; 10) en (60; 30). Oud E₀ = (30; 14), nieuw E₁ = (21; 17). De horizontale pijl vergelijkt aanbod bij P = 14 van 30 naar 12. De andere pijl ligt langs de ongewijzigde vraaglijn. De hoeveelheid daalt 30%. Prijs 17 ligt in beide domeinen.','Waarom vragen kopers minder zonder dat hun vraaglijn verschuift?','De metaalprijs verschuift A, de prijs van de sleutelhanger laat kopers langs V reageren.','Vergelijk de twee afzonderlijke scenario’s.',true);
}
{
const s=ex('Dezelfde prijsstijging, een andere hoeveelheid');table(s,[['Alleen deze oorzaak','Prijs','Hoeveelheid per week'],['Meer kopers','€ 14 naar € 17','30 naar 39'],['Duurder metaal','€ 14 naar € 17','30 naar 21']],60,281,1480,313,[610,380,490],35);text(s,'Een prijswaarneming alleen bepaalt de oorzaak niet.',60,675,1480,87,45,{bold:true,color:C.blue});notes(s,'110','Allebei beginnen bij hetzelfde E₀. De vraagverschuiving laat P en Q stijgen. De aanbodverschuiving links laat P stijgen en Q dalen. Alleen binnen de gegeven afzonderlijke-oorzaakmodellen kun je deze richtingen zo afleiden.','Welke extra waarneming helpt om de twee verklaringen te onderscheiden?','Prijs en hoeveelheid alleen bewijzen zonder modelaannames niet welke specifieke factor veranderde.','Combineer voor de volgende korte verkenning twee oorzaken, zonder getallen te verzinnen.',true);
}
{
const s=ex('Twee oorzaken zonder bekende omvang');text(s,'Nieuw scenario: minder kopers én duurder metaal.',60,262,1480,66,40,{bold:true});table(s,[['Bekijk eerst afzonderlijk','Prijs','Hoeveelheid'],['Alleen minder kopers','Daalt','Daalt'],['Alleen duurder metaal','Stijgt','Daalt']],60,381,1480,262,[780,350,350],35);text(s,'Samen: Q daalt. De richting van P is nog onbepaald.',60,698,1480,74,41,{bold:true,color:C.blue});text(s,'Tegengestelde druk betekent niet automatisch gelijke effecten.',60,790,1480,46,32);notes(s,'114','Een afzonderlijk kwalitatief uitlegvoorbeeld ter voorbereiding op de combinatiebewerking in basis 27. De dalende vraaglijn en stijgende aanbodlijn schuiven nu allebei naar links, met onbekende omvang. Beoordeel eerst elke oorzaak apart. Beide effecten verlagen Q. Voor P werken ze tegengesteld, zodat P kan stijgen, dalen of gelijkblijven afhankelijk van de omvang. Dit is geen uitwerking van campinglampenopgave 27: de richtingen en context verschillen. Het boek behandelt enkelvoudige veranderingen expliciet op 108–111 en introduceert de begrensde dubbele verandering in 27.','Is onbekend hetzelfde als onveranderd?','Twee tegengestelde effecten hoeven elkaar niet precies op te heffen. Er is geen gegeven getal waarmee je de nieuwe prijs kunt berekenen.','Keer terug naar start 24 en begin daarna bij 25.',true);
}
overview('Zelfstandig werken',4);
{
const s=target('Opgave 31 · Meer kopers van oplaadkabels',true);text(s,'Een regionale markt. Q is kabels per week. P is euro per kabel.',60,208,1480,87,38,{bold:true});table(s,[['Beginsituatie','Functie','Domein'],['Vraag','Qᵥ,₀ = 100 − 5P','0 ≤ P ≤ 20'],['Aanbod','Qₐ = 5P − 20','4 ≤ P ≤ 24'],['Nieuwe vraag','Qᵥ,₁ = 120 − 5P','0 ≤ P ≤ 24']],60,352,1480,346,[430,610,440],35);text(s,'Er komen meer kopers. Alleen daardoor verandert de vraag.\nDe omstandigheden van de aanbieders blijven gelijk.',60,744,1480,96,35,{bold:true});notes(s,'116','Volledige werkelijke context en gegevens van doel 31, uit de tweede editie. De volgende dia’s tonen de gegeven figuur en alle vragen zonder antwoorden. Start de bespreking pas na een zelfstandige poging.','Welke omstandigheden noemt de bron als veranderd?','Gebruik niet de eigen uitleggegevens van sleutelhangers. Dit is de markt voor oplaadkabels.','Toon de oorspronkelijke figuur en daarna alle deelvragen.');
}
{
const s=target('Opgave 31 · De gegeven beginlijnen',true);graph(s,T,'base');text(s,'V₀: Qᵥ,₀ = 100 − 5P\nA: Qₐ = 5P − 20',1110,286,420,143,33,{bold:true});text(s,'De oorspronkelijke\nlijnen zijn gegeven.\n\nDe nieuwe lijn en\nuitkomsten ontbreken.',1110,496,420,232,35);notes(s,'116','Dezelfde beginlijnen, assen, bereiken en eenheden als figuur 24. Geen evenwichtmarkeringen of nieuwe vraaglijn vooraf. De gegeven figuur blijft terug te halen tijdens de bespreking.','Waar staat de hoeveelheid, en waar de prijs?','De vraaglijn loopt maar tot P = 20, hoewel de prijsas tot 24 doorloopt.','Toon a tot en met c zonder oplossingen.');
}
{
const s=target('Opgave 31 · Deelvragen a, b en c',true);text(s,'a) Bereken het oude evenwicht en controleer met beide functies.',60,217,1480,105,41);rule(s,60,351,1480);text(s,'b) Benoem de specifieke factor. Bereken na de verandering beide plannen bij de oude prijs en verklaar de prijsdruk.',60,394,1480,159,39);rule(s,60,588,1480);text(s,'c) Bereken het nieuwe evenwicht en controleer. Bereken de procentuele verandering van Q.',60,642,1480,150,41);notes(s,'116','Dit zijn de volledige reken- en verklaringsvragen a, b, c. Vraag b heeft drie handelingen, vraag c zowel controle als percentage. Nog geen antwoorden totdat d en e ook zijn getoond.','Welke stappen vraagt b naast rekenen?','Een nieuw evenwicht alleen is geen volledig antwoord op c.','Toon de tekenvraag en beoordelingsvraag.');
}
{
const s=target('Opgave 31 · Deelvragen d en e',true);text(s,'d) Voeg V₁ toe. Markeer E₀ en E₁ met coördinaten. Laat met pijlen de verschuiving bij de oude prijs en de beweging langs A zien.',60,240,1480,181,42);rule(s,60,466,1480);text(s,'e) Beoordeel: “De grotere aangeboden hoeveelheid komt door een verschuiving van de aanbodlijn.”',60,541,1480,174,42);notes(s,'116','Nu zijn alle subvragen en de complete context beschikbaar zonder oplossingen. Laat leerlingen hun eigen poging erbij leggen. De d-vraag vereist twee verschillende pijlen.','Wat moet de eerste pijl gelijk houden?','De figuur moet zowel de verschuiving als de beweging langs A tonen.','Begin bij het oude evenwicht.');
}
{
const s=target('Opgave 31a · Het oude evenwicht');lines(s,['100 − 5P = 5P − 20','120 = 10P','P₀ = € 12 per kabel'],{y:217,gap:110,size:46});rule(s,60,555,1480);text(s,'Qᵥ,₀ = 100 − 5 × 12 = 40\nControle: Qₐ = 5 × 12 − 20 = 40 kabels per week',60,608,1480,138,42);text(s,'E₀ = (40; 12)',60,785,1480,53,37,{bold:true,color:C.blue});notes(s,'116','Tel 5P en 20 aan beide kanten erbij, deel door 10. Controleer beide functies afzonderlijk. P = 12 ligt in beide opgegeven prijsgebieden. Qv en Qa zijn dezelfde 40 transacties in evenwicht, niet 80.','Waarom gebruik je hier nog 100 − 5P?','Het oude evenwicht hoort bij de oude functies.','Onderzoek daarna de gewijzigde vraag bij de oude prijs.');
}
{
const s=target('Opgave 31b · Aantal kopers en prijsdruk');text(s,'Specifieke factor: het aantal vragers neemt toe.',60,214,1480,74,42,{bold:true,color:C.purple});table(s,[['Bij P₀ = € 12','Invullen','Uitkomst per week'],['Nieuwe vraag','120 − 5 × 12','60 kabels'],['Ongewijzigd aanbod','5 × 12 − 20','40 kabels']],60,358,1480,283,[520,460,500],35);text(s,'Vraagoverschot: 60 − 40 = 20 kabels per week',60,694,1480,73,43,{bold:true});text(s,'Kopers concurreren om het aanbod: opwaartse prijsdruk.',60,785,1480,51,34,{color:C.blue});notes(s,'116','Meer kopers betekent bij dezelfde prijs meer koopplannen. Aanbieders hebben bij P = 12 nog hun oorspronkelijke plan. Het vraagoverschot van 20 geeft opwaartse druk als de prijs zich kan aanpassen.','Waarom vergelijk je 60 met 40 en niet met de nieuwe evenwichtshoeveelheid?','Voor prijsdruk vergelijk je de nieuwe plannen bij dezelfde oude prijs.','Bereken waar die nieuwe plannen weer samenvallen.');
}
{
const s=target('Opgave 31c · Het nieuwe evenwicht');lines(s,['120 − 5P = 5P − 20','140 = 10P','P₁ = € 14 per kabel'],{y:219,gap:108,size:46});rule(s,60,551,1480);text(s,'Qᵥ,₁ = 120 − 5 × 14 = 50\nControle: Qₐ = 5 × 14 − 20 = 50 kabels per week',60,606,1480,145,43);text(s,'E₁ = (50; 14)',60,784,1480,52,38,{bold:true,color:C.blue});notes(s,'116','Gebruik V₁ en dezelfde A. Tel 5P en 20 op aan beide zijden, deel door 10. P = 14 past bij de domeinen van de nieuwe vraag en aanbod. Controle in beide functies geeft 50.','Welke functie bleef gelijk tussen a en c?','De stijgende prijs verschuift A niet.','Vergelijk de oude en nieuwe evenwichtshoeveelheid.');
}
{
const s=target('Opgave 31c · De procentuele verandering');table(s,[['Oude hoeveelheid','Nieuwe hoeveelheid','Toename'],['40 per week','50 per week','10 per week']],60,219,1480,214,[500,500,480],37);text(s,'(nieuw − oud) / oud × 100%',60,494,1480,80,47,{bold:true});text(s,'(50 − 40) / 40 × 100% = +25%',60,612,1480,85,51,{bold:true,color:C.orange});text(s,'Controle: 25% van 40 is 10. 40 + 10 = 50.',60,762,1480,73,39);notes(s,'14, 116','De basis is de oude evenwichtshoeveelheid 40. De stijging van 25% is relatief. De absolute stijging is 10 kabels per week. De 60 uit b is een vraagplan bij P = 12 en geen nieuw evenwicht.','Waarom staat 40 onder de breuk?','Gebruik niet 60 als nieuwe hoeveelheid of 50 als vergelijkingsbasis.','Teken de nieuwe vraaglijn met twee berekende punten.');
}
{
const s=target('Opgave 31d · Twee punten voor V₁');table(s,[['Gekozen waarde','Berekening','Coördinaat (Q; P)'],['Qᵥ,₁ = 0','0 = 120 − 5P, dus P = 24','(0; 24)'],['P = 0','Qᵥ,₁ = 120 − 5 × 0 = 120','(120; 0)']],60,225,1480,310,[410,660,410],34);text(s,'Verbind de punten met een rechte lijn en label V₁.',60,605,1480,91,43,{bold:true,color:C.purple});text(s,'Markeer E₀ = (40; 12) en E₁ = (50; 14).',60,746,1480,80,42);notes(s,'97–98, 116','De coördinaten hebben Q eerst en P tweede. Beide punten zijn domeingrenzen van V₁. Dit zijn lijnpunten, geen evenwichten. Markeer daarna de twee berekende evenwichten.','Waarom is (0; 24) het snijpunt met de prijsas?','P = 0 invullen levert het horizontale snijpunt, niet de evenwichtsprijs.','Voeg de nieuwe lijn, beide evenwichten en daarna de pijlen toe.');
}
{
const s=target('Opgave 31d · Beide evenwichten');graph(s,T,'new');text(s,'E₀ = (40; 12)\nE₁ = (50; 14)',1110,282,420,150,42,{bold:true});text(s,'V₁ door\n(0; 24) en (120; 0)',1110,490,420,135,36,{color:C.purple});text(s,'De schalen en A\nblijven gelijk.',1110,709,420,109,36,{bold:true,color:C.green});notes(s,'116','De oude en nieuwe snijpunten liggen allebei op A. De nieuwe vraaglijn snijdt de prijsas bij 24 en de hoeveelheidas bij 120. De hulplijnen tonen 40/12 en 50/14.','Waarom liggen E₀ en E₁ niet op dezelfde vraaglijn?','E₁ hoort bij V₁. V₀ beschrijft de oude kopersgroep.','Voeg afzonderlijk de oorzaakpijl en de reactie op A toe.');
}
{
const s=target('Opgave 31d · Twee pijlen, twee betekenissen');graph(s,T,'arrows');text(s,'Verschuiving bij € 12:\n(40; 12) naar (60; 12)',1110,271,420,166,35,{bold:true,color:C.purple});text(s,'Beweging langs A:\n(40; 12) naar (50; 14)',1110,514,420,170,35,{bold:true,color:C.orange});text(s,'Oorzaak en prijsreactie\nblijven gescheiden.',1110,749,420,91,33);notes(s,'116','De horizontale pijl begint op V₀ en eindigt op V₁ bij dezelfde P = 12. A is bij de oude prijs nog 40. De oranje pijl volgt A van E₀ naar E₁, doordat de hogere kabelprijs de aangeboden hoeveelheid vergroot.','Welke pijl eindigt bij 60 en welke bij 50?','De 20 extra vraag bij oude P is niet de 10 extra evenwichtshoeveelheid.','Gebruik de ongewijzigde aanbodfunctie voor de beoordeling van e.');
}
{
const s=target('Opgave 31e · Groter aanbod langs dezelfde lijn');text(s,'De uitspraak is onjuist.',60,223,1480,85,51,{bold:true,color:C.orange});text(s,'A blijft Qₐ = 5P − 20.',60,362,1480,72,47,{bold:true,color:C.green});table(s,[['Prijs per kabel','Aangeboden hoeveelheid'],['€ 12','5 × 12 − 20 = 40 per week'],['€ 14','5 × 14 − 20 = 50 per week']],60,474,1480,236,[500,980],37);text(s,'De aanbodfactoren blijven gelijk. De prijsreactie ligt langs A.',60,762,1480,77,39,{bold:true});notes(s,'116','De specifieke oorzaak ligt aan de vraagzijde: meer kopers. De hogere prijs is het gevolg daarvan. Aanbieders reageren op die eigen prijs langs A. Een grotere aangeboden hoeveelheid en een grotere vraag bij dezelfde prijs zijn verschillende verschijnselen.','Welke bronzin sluit een aanbodverschuiving uit?','Een stijging van Qₐ alleen is onvoldoende bewijs voor een nieuwe aanbodlijn.','Laat leerlingen hun eigen uitwerking controleren en het huiswerk noteren.');
}
overview('Afsluiting / huiswerk',7);
await fs.writeFile(path.join(BUILD,'manifest.json'),JSON.stringify({...M,slides,overviewSlides:slides.filter(s=>s.role==='overview').map(s=>s.number),nativeTables:tables,nativeCharts:charts},null,2));
await fs.writeFile(path.join(BUILD,'graphs.json'),JSON.stringify(graphs,null,2));
await fs.writeFile(path.join(BUILD,'presentation.json'),JSON.stringify(p.toProto()));
const draft=path.join(BUILD,'candidate.pptx');await(await PresentationFile.exportPptx(p)).save(draft);
execFileSync(PYTHON,[path.join(TOOLS,'notes-font.py'),draft]);execFileSync(PYTHON,[path.join(TOOLS,'straight-scatter.py'),draft]);
const result=await finalizePresentation({workspaceDir:ROOT,candidatePath:draft,finalPath:path.join(FINAL,'1.3.3 '+TITLE+' – presentatie.pptx'),pythonExecutable:PYTHON,integrityValidatorPath:path.join(SKILL,'container_tools/inspect_presentation_package_integrity.py'),layoutValidatorPath:path.join(SKILL,'container_tools/inspect_presentation_layout_geometry.py'),layoutArgs:['--expected-slide-size-emu','15240000,8572500','--validate-bullet-geometry','--validate-heading-fit',...tables.flatMap(n=>['--require-native-table-slide',String(n)])],fontPolicy:{basis:'design',families:[FONT]},requiredNativeTableOwnerSlides:tables,requiredNativeChartOwnerSlides:charts,materializeLiteralChartWorkbooks:true,verifyArtifactToolImport:true,receiptPath:path.join(BUILD,'validation-final.json')});
console.log(JSON.stringify({slides:slides.length,finalPath:result.finalPath,package:result.packageIntegrity.status,layoutFindings:result.presentationLayout.findingCount,import:result.firstPartyImport.passed}));
